apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fireflyiii-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: fireflyiii-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: app_key
      remoteRef:
        key: prod/apps/fireflyiii
        property: app_key
    - secretKey: site_owner
      remoteRef:
        key: prod/apps/fireflyiii
        property: site_owner
    - secretKey: static_cron_token
      remoteRef:
        key: prod/apps/fireflyiii
        property: static_cron_token
    - secretKey: redis_password
      remoteRef:
        key: prod/apps/fireflyiii
        property: redis_password
    - secretKey: db_password
      remoteRef:
        key: prod/cnpg/databases/fireflyiii
        property: password
    - secretKey: db_username
      remoteRef:
        key: prod/cnpg/databases/fireflyiii
        property: username