apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: gotify
      app.kubernetes.io/component: notification-server
      app.kubernetes.io/part-of: goti-stack
    

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - cilium-netpol.yaml