apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-data-pvc
  namespace: goti-stack
spec:
  accessModes:
    - ReadWriteOnce   # use RWO for SQLite stability
  resources:
    requests:
      storage: "32Mi"
  storageClassName: longhorn
