apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fireflyiii-upload
  labels:
    app: fireflyiii
    tier: frontend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi