---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pgadmin-credentials
spec:
  encryptedData:
    PGADMIN_DEFAULT_EMAIL: AgBwNH/2Mdb177L/BaCIVtFLz9v4oH+e39fchePI9DGAZeJlJCQhtVZbeIcTLQbWUbDb0uMxv1/r6rOIUP801bEg3KJV7Q56CcAEAE7EGmTlkFPaSz4TBjrAJKSWjXUi+ASsGyYdK7TwWeaDVYXieRAjFb9zct9yD54x26YTtfH99yvE+oSY2KGUqWhGxqdnDPfh3kqDr1JX8sWvoU6pyV5eHTIEH8A7IOA5DlVd5B4fkv7GwHdOPcA2wK46+VQXZjIZdwzqCbC8n2i0tP1MwNJOz2/pkfP/KN75O/M4QqFqZF4okhOYQME+8K8L8IGFDqTSC4H2Q9jcbhWkk2fsqpZAnUScvWIjltQlk7JxjPSLIdqe/eyHPkvtHIEly6w6cbZtv7KnNdFZn9dZ8LYk3A/+J9JjMhOQnN6OffsKe0zuh0BMzf1x6XsQZf1ln47mDmc4i1gbdDb9ZmbGEvpRxkcZgqLrKLZ79IlImCYOkivaAkYd4S1tWMuQKl/X5uiaoR3kh0jn60YnzMzQ/4RwrE0k6M6Vj1sqpBRl1S7z147Y1dV4FcbBSF/0Op5kSF6x/1syIxxldlC898oxCsNCRb4FUUIfZ9mqbqzFy7qVKCnw4FTVFf6ztiKm7xX+QV7CI18GbEhBq/JBT8hKoFNFP6M0AY+o1RMmoJnRvB+JqtA9KJXRLoqTFAnJFhsoRpAOW0owqy6UOIumhJ7NqGgGSekUikmID4gqZXw=
    PGADMIN_DEFAULT_PASSWORD: AgAUPfFy1fqog+ICcTk1Zf/TGghDjPrpilEn9HRJX6jzXhKKV2L2SLK+5e0zREgnCT0+qt9Mu9Nm5WFvas1Acm2Lx0HDwAwvQdUYRQlCaM4OndruhZvGTGTwe33AYqA1Q7LVnbmrmQVo1oOvRIEEtLzNo6laoVuGL/VmnUVtlfpFH8y0qD/lA5OnVn27cCUl+xHz2MFLIyBj6tZlhwsUK7V4LIY1GZGRzT2QThomCdOzeWJE8QCc99uuNQ06JKKbnBwk+49a5DQy0JZ4nd0rehsi7LhQE1ZEOeptbdADUcAlLlQG9wtSnF896IGO8OB5I9Cc2oxAbvKFwp+AlQGTosrgVE88MGwleHOLsmmmu3hRv4ub5BOP8rLzErBQoapx8HNANhlzyKO4pRbKodLtdrFMN46TDfntwp5HGtVqw6WcZLQetPhBb8vsmyIkxDvG6Kh+u/ju43HEzrvIaHrlW8Me7ik5aDWboEaq3WY3RmxGcOWD1Ji4LipUacIj6NFSA7OBcUQdpCILVCR167LYZRLlnQ0X15KiglZU4FcHAjrn9O91UgXGzZ5dLmqTvZhDHFoW5Hds0ly22isTLuX2xkKwbgZ2z7HyxrSkX/b6NxqG3yPTObwLtQRJLPApLZFyUjVjVzqLayRE3lZGJchaNMF/m6vb0bKW+iVp4lIhf91oUwzXI6ZVUqyzUaQcys+YXjVuRJUglwYRN4AeQnVKxUdDXQU0XeVtAdZT9PYK0UI4BA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pgadmin-credentials
