---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pgadmin-credentials
spec:
  encryptedData:
    PGADMIN_DEFAULT_EMAIL: AgC5HcUTqNrMWwqAoUAyy2lE9EA0Shn3JozhVaQbwdvz929wNGM6Q1RfqHAjGS93RL1Plk+jXmXUjoXMBLH07E85ijANCxF6FkmJGbp8Sgdp3a0jH2UU+0iRDaU6vqupHKnjTLaMolb0oChdliUINFq2eGAJTqeVNll4FZXfQVmkzeHm7egkCQDdTz8tUqO/SXsvTm76o3TJ/WyhXBNjqdzD6LRaW0i62zZElAOltamj/XPOyEyFyNQZ3AGQBpS8EQj8g8+mV1iDK8Mpf0vlJ+qrIPCPi/PGoGorMeUs/yAkxdCr6INeWekMzQaQEuzKkmbUEoCJPOfP7tfiL1dOy7/0LMw1b0a/sFFfH+SQ1E/PgYeNrdT9jk7ArFnGmfW6nkHASfzTNKiSR6+RBXH4QJmxAYQYOwbe50sBKDF49P1T+8kN4rxglHvLIyhRHAxHxUKAhhgdn29v+5Hdvj/jjhtv6TOVFgw8uuNitisO3yAEZ38rJMAgvSXTP48LyDuD8MbhnX/4HdB7VBg3jGqmycCF+RopIBj88FZWs+sy3eXtEom09u8xb1l7F8HzCF+y2xZnTv3NLqA1BxqUSpr6Zma3dS/4jhs1XLkA7VExTojFJ3jIjHy8WEc2XZUHKEXjyPT2297Q4UfAiZuHsqY8+lCkBT5S+aJP3pdDUWFhPErxsJcaSsTZNQ/jNYotLSxIq5JnJvnQef6yuBWYnCeFL1nr1Kyx5er5DZc=
    PGADMIN_DEFAULT_PASSWORD: AgA31InGTe0iO7wWVlCKbJVMEBa0OyyYVT1KUgoJko+KLxFgS1u7gr8KcNp+ERsLs9VuE4RgpHmwucKMnh3m526HoPvNB08N/zDpDvBYgrjRKHWfwaaivBuHpdIPaS/h+FGRvrDq5/6bcu+Oz44Dnzdsa2h3528MLf2Y0cHIvZVknJ9k2SDkPJMTbousIj4pVXWhhdk8fkUcFN0bAJMdCD581BrOEM3gXeUM01EYwWuJaY/XoKND71/vf+QLR4vB/2QvkiPLCXBWro0QmJDRn5Xpgw3MKV4Kmr4OKe9HWn6ar8sX6CHXFXpWF3PRyeyB1aaUzi34wlXjFFPMn0lZOPIAoXbKAGEoJ/IFqKATvRWV48PSLk6+g86T8WKdU7Lgb50u2wuuZ5Leo4yS7QruebJpqIXwdiXVzoKdbgfb5yR/bLuiYllNfKP+26db/lbgec1BwlsDgYSB4AddZdKWzcdYwQ3wP5D52pE9te60KyfgAg2ChOdHD2yzQNwIwgu/sizcqpa0/mVCBZAuh6l+utq5gqwJVCo+L7F809hrt171VDVbNGCzN6ao503HzrmuOZ9hOTj4r9aRNJT3dbRS1UECXgouWtu2VTjUgYcSMlQUjPt+WL+aIcOaTwOvk49qEErXcPdJu+FKsBvs8DadjN3N5J//POvXbPMDs5uZrYjW3t0DgYeR2lAY+pSpXIrI+D8n6a+aaHfRzDBjt85YeEHymtd8ZIVTLkSiBLejbO079Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pgadmin-secret
