apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "https://secrets.tamhomelab.com"
      path: "secrets"
      version: "v2"
      auth:
        # AppRole authentication method
        appRole:
          path: "approle"
          roleId: 7d34b534-4579-2638-617b-aa3f38ab5f93
          # The name of the Kubernetes Secret containing the AppRole SecretID
          secretRef:
            namespace: eso
            name: vault-approle
            key: secret-id