apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: karakeep-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: prod/apps/karakeep
        property: MEILI_MASTER_KEY
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: prod/apps/karakeep
        property: NEXTAUTH_SECRET
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: prod/apps/karakeep
        property: OPENAI_API_KEY