apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fireflyiii

labels:
  - pairs:
      app.kubernetes.io/name: fireflyiii
      app.kubernetes.io/component: importer
      app.kubernetes.io/part-of: fireflyiii
    
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml