apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: egress-to-redis-db-metrics
spec:
  description: Allow egress to Redis databases metrics
  endpointSelector:
    matchLabels:
      netpol.cilium.io/egress-to-redis-db-metrics: "true"

  egress:
    # Allow egress to any Redis instance across all namespaces
    - toEndpoints:
        - matchLabels:
            k8s:app.kubernetes.io/name: redis
            k8s:app.kubernetes.io/component: cache
          matchExpressions:
            - key: k8s:io.kubernetes.pod.namespace
              operator: Exists
      toPorts:
        - ports:
            - port: "9121"
              protocol: TCP