apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: firefly-core-netpol
spec:
  description: >
    Allow Firefly III core pods to egress to the CloudNativePG
    database services (rw, ro, r).
  endpointSelector:
    matchLabels:
      app: fireflyiii
      tier: core

  egress:
    - toEndpoints:
        - matchLabels:
            io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name: cloudnative-pg
            cnpg.io/cluster: fireflyiii-database
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
      