apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: homepage-vars
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: HOMEPAGE_ALLOWED_HOSTS
      remoteRef:
        key: prod/apps/homepage
        property: HOMEPAGE_ALLOWED_HOSTS
    - secretKey: HOMEPAGE_VAR_BASE_DOMAIN
      remoteRef:
        key: prod/apps/homepage
        property: HOMEPAGE_VAR_BASE_DOMAIN
    - secretKey: HOMEPAGE_VAR_PROXMOX_USER
      remoteRef:
        key: prod/apps/homepage
        property: HOMEPAGE_VAR_PROXMOX_USER
    - secretKey: HOMEPAGE_VAR_PROXMOX_PWD
      remoteRef:
        key: prod/apps/homepage
        property: HOMEPAGE_VAR_PROXMOX_PWD