apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage-sa
  namespace: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: homepage-role
  namespace: homepage
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes", "gateways"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: homepage-rolebinding
  namespace: homepage
roleRef:
  kind: Role
  name: homepage-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: homepage-sa
    namespace: homepage
