apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: homepage
  namespace: homepage
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes", "gateways"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: homepage
  namespace: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage-ns
