apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
spec:
  selector:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: homepage