apiVersion: batch/v1
kind: Job
metadata:
  name: nextpvr-update-credentials
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: job-exec-sa
      restartPolicy: Never
      containers:
      - name: updater
        image: lachlanevenson/k8s-kubectl:latest
        env:
          - name: NEW_USERNAME
            valueFrom:
              secretKeyRef:
                name: nextpvr-credentials
                key: username
          - name: NEW_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextpvr-credentials
                key: password
        command:
          - /bin/sh
          - -c
          - |
            POD_NAME=$(kubectl get pods -n nextpvr -l app=nextpvr -o jsonpath='{.items[0].metadata.name}')
            MD5_PASS=$(echo -n "$NEW_PASSWORD" | md5sum | cut -d ' ' -f1)
            kubectl exec -n nextpvr $POD_NAME -- /bin/sh -c "
              sed -i 's|<Username>.*</Username>|<Username>$NEW_USERNAME</Username>|' /config/config.xml && \
              sed -i 's|<Password>.*</Password>|<Password>$MD5_PASS</Password>|' /config/config.xml
            "