---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: nextpvr-credentials
  namespace: nextpvr
spec:
  encryptedData:
    password: AgB3Ngszgm3Dk9wCGAJmQ738uLm351v7a0u8KTaTaKpskJjSFzSMHLKFxrjMCfCkC8KaaPXKx4lMuTMtkXHJyAoUmNTDbbrbhrAgMBU0l4H+1rKhb04/Fh/0HsqJGuKnJZC1ioHBGoQtCpX/Vxhdo6i4Yr0I8c6x+TOAuseoBQ8R1jmEh4HqgBFotBjBdFYXJSu9OemBsOupxElLbb+JQyoIsx+eFW7fcPWMaWgVU6TnM2cv0rLEUY6UtyUH3FOomVRFWl4Rgh0Z3gNwwHEZjWJSIsIofkIdHBlRCti3YTy1uBYqj5iUsj+FS65dJu2Pz1509Q0BYkU+EE32oY9PbXhoa69VTg63AwnEfNlrmHmKXrOpzboyLCO+HYQ6TqymMXMkS/Q43poo/dDaSVG1ezfyG02pHUOwC1ROnRFrlrfeC4zYZybRV2uRoan3QbzdvjCEuxCJ2EeuTcvxru82EIDK7YV7oYRnNxI9R71QmsM9PHn/tBryHe2claCtVa2IuBQNqb6PolldyRHWBe5UyAro1Kq4cgS/8snYnSJGLbaKFtRdSqi3qxz6xWNTtkUuDdOxhIi3ZaJYZY00ZtGYz/MGpSGOIez0D8GEhtJvDjF7K0xZUI5zdaiQs5ONxJut2vJ8OUyeRyjguPjgBx9ts6glifKX/cCcJR8NspwvX7bkUcMteD8aihqyoBCahoedw7s8LWrfCW9etuBDeyEy2dKb
    username: AgCbAAxEmzTiA5B5fpiR1SV4U8KgdFdtUs7OAtXIzgnnhZm04wQzd2C9MR/lAkYwGCXNnqJ0ghfezLU/tsbzOzilVVzfkVK9msMZR59Z/36Ds5lB7eCe2XFZyCivbP8FqpOG6Z3GPUv7rCuuN1e5W8yqfCPA69uUzcDwWYeCYi8gjys53dXzix7nthp0/pkUfZVr8xBqR5huF0nNbS+RmCgYprtXfWO+P0BFvael1ymlboi2OpLXwQVF4Jw8TiFNiJWPq1tRj3MpmvNyHs9St9s2HkL3Rg16ije3dJUyx8LRs3tviviHoPekVQyoNbJ4xYhgosDxZ2VlzFjUxHXSmOKGGDYHsTUV6wqXxNTRsaJmBV9yoEliqYBAE76TLMSU0U+u9fHllJO0wQG468J/t5Lyvpt/X0+WSyXxAUfnL1lA4j6qHCky0SSQF1Cf5cQaYxHkvYawwN0kUJSkYIbG99rW12KYCgDMwB3zR7ShXXx/MOtJk2vJFzOEJ2cMOBvLitOrDdeLpaSRKoE1MkuGx5sBpuLZQaJV0m0+Fb7ThqYLfWXmqUhJLyKEJluLpCN1ZN8hwMbUlXsbwNw89ioSbZcEmw81Y5hjcl3YhB6sgtBs/iYi2vaxR2dM2ZNYr9Czn+zjq0YY+eeZf5x3m41nKjzrMjiB+WmcDL6NSIJg+JOLr9kucz2oRJfTcrPAOVz9YEOJAn4M5sJB
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: nextpvr-credentials
      namespace: nextpvr
    type: Opaque
