apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextpvr-pvc
  namespace: nextpvr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
