apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-driver
  labels:
    app: web-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-driver
  template:
    metadata:
      labels:
        app: web-driver
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: web-driver
          image: selenium/standalone-chrome-debug:3.141.59
          ports:
            - containerPort: 4444
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi