---
- Social:
    - Instagram:
        - icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/instagram.svg
          href: https://instagram.com/
    - WhatsApp:
        - icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/whatsapp.svg
          href: https://web.whatsapp.com/
    - X:
        - icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/x-light.svg
          href: https://x.com/
    - Reddit:
        - icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/reddit.svg
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/youtube.svg
          href: https://youtube.com/
    - Manga:
        - icon: https://www.natomanga.com/images/logo-manganato.webp
          href: https://www.natomanga.com/
    - 9GAG:
        - icon: https://upload.wikimedia.org/wikipedia/commons/4/42/9gag_logo.svg
          href: https://9gag.com/