---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

#- resources:
#    cpu: true
#    memory: true
#    disk: /

- kubernetes:
    cluster:
        show: false
        cpu: true
        memory: true
        showLabel: true
        label: "cluster"
    nodes:
        show: true
        cpu: true
        memory: true
        showLabel: true

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
      timeStyle: short