apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
labels:
  tamhomelab.com: app-managemet
  app.kubernetes.io/managed-by: argocd

resources:
  - project.yaml
  - application-set.yaml