apiVersion: v1
kind: ServiceAccount
metadata:
  name: gotigram-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gotigram-secret-manager
rules:
  # Allow the init container to create/update the gotigram-token secret
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["gotigram-token"]
    verbs: ["create","update","patch"]
  # Allow the init container to get/list secrets (to check if gotigram-token already exists)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gotigram-secret-manager-binding
subjects:
  - kind: ServiceAccount
    name: gotigram-sa
    namespace: goti-stack
roleRef:
  kind: Role
  name: gotigram-secret-manager
  apiGroup: rbac.authorization.k8s.io
