---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: barman-s3-credentials
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCRCI+WR6wrYcQMxcG7WQEek1kXNJmOrKB1yl2XaBZ2HPZ3rpCFuqpsIyUZtsWgAPI929O8XSSKyoPkEdWbBBOfbX1yJyNdUcybstxbd7wqWwHRifcG36QWhAwAb2lZXjUFVteUlhTxBLiX5uK0eeiwSE7VXb9I9NZPyKw7QqoyI0LJtx/gNijm7HLFMquXkmXALLC/fC8UQdHsNn+LVPt6tNQwDqSiEPX1P7AX0kknjMJPTqBsKj00JSGrZVlW/ovwMGRPHg0C+4fbz2W9vTQ0YReYBLyYibFNJrNBgYCROudPd/YI2UHQNyNGh7mIN+PYr1Toalukn/nSN/tOAaUBj3znuO1YA7rLnVGgZa3g62yoR9VGK4IgQcdKDl35zbnUUIFbJBq9HumujiykZjFtJK5cQfrBetB5icp9omaumLamWoNNpjomR8Ptuua6jicr2sN01/z514NPFMTFEheLKv6Xe9cYdEvdL0S/ZBIHr4XrrRyOmQYG2dTdRhHo1/1RRUyCVIVkgFd0JkLNd9p8wWlMBZWvy8Ac1ISmlwMrmhaTtscOPOditQqDSkt8WXMKtc07etSzI8LOtOP0oTlOZL4RdDNQlm/W341uPOhVgjDQY8fziNlUuN/MClTbDggBNCS/mp0cFlY9Db3zFVcT2yWDki0DVgvzQedrbuTfFI6avFZPMg6im7qHwl0LcpqzSrYo7RkXDhMVhMU4y/RksxWfYDTbjkHcc4dFXKcuhQ==
    ACCESS_SECRET_KEY: AgB+9XkBSSZmT9uCn/fkarNdPSFb6Inf4+QloBIIvHHB5A5/Pt8bz65KPtXEOm0jwiFy/PAVpMhP+lx4ueV8p/Q+cQCcw9Y22hSdaoXuhX0butIkO9xDrW2W81XzCzW01elYhnb3UFJHdYW560YWv9IHNKLn7AdfVeYzyVDhSOXnxRK/asvlKwFaWh8iDZEcJqrBMgF/PsKNCGmKZxgDh+3lhFzOrtafLMl4sfg/Mm6L9+EDTm6b4TJ+1bOEn7yCUg4m9cvRRqKyZevgRHh87PESx29nVd8akva3ty+6We6LdeX5GULtpiRkSiJZb7JuMlG8ZoqNSWh1Sf9Yi9wAC+fzEVKyrLdVBPqRghdu7y8BJ/64NgLf2JhPLBVvZ2mn8nWy56/oOVDryX0+BBXPaerZTrV3cL5RTWB5DyYMVzKOLzKqnDxLGcmPGZMqpun4L32YHlzWTgAoogC9oViOMUFSCZ6DQBdY9yvBiKg4xc5i540nllias3bI2BA0XnklII48oqOO38cArHBCtp0AVLqH4xg1o3yz7954ouXMbz6GMswKZO5Agiu3EJVJPyTbW7ORJxOO32u3nTbaA4DLceivHp1cdTXLh4glCw7SF9O8lyOJ2jKtB3ulv8/O0EvMeb4AwWnwnJNtOmAWoebpDtQTNyRkdaolyp/Qc+YIN09QLs1uws0wgEvWxyMiFjdSH30YiTcEGyQ/KgVwSDpwQLXC9rnRsNyxlhT5mOYpGew1B635ijJRsyc2F6/3YQM0uie7LDP6P18nzd7Clhcqk4dc
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: barman-s3-credentials
