apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg

labels:
  - pairs:
      app.kubernetes.io/part-of: infrastructure
      
resources:
  - barmanObjectStore.yaml
  - s3-credentials-external-secret.yaml

helmCharts:
  - name: plugin-barman-cloud
    repo: https://cloudnative-pg.github.io/charts
    version: 0.8.0
    releaseName: barman-cloud
    namespace: cloudnative-pg
    valuesFile: values.yaml
    includeCRDs: true

patches:
  # Enable Stakater Reloader for automatic reloads on ConfigMap/Secret changes
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /metadata/annotations/reloader.stakater.com~1auto
        value: "true"