apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credentials-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: s3-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: prod/cnpg/barman
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: prod/cnpg/barman
        property: ACCESS_SECRET_KEY