---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAejLisnR/g8cQd0XFUDXCUfAunHSW/5IHDUOxo/xUTAj05Y6WgbkWNxytLS9jB30djs5zn+RUYw5mNvs6/zCYzV/+jfqhyZ8ANjnNUNCbUYc0IIYxDBppvAHVU5yloRy+ZxrqCdFVIHI+WxOjTVd643Wpn0Orm10Ky5VJW4iuSg8K/VkxOja2dHTe0ms0JXGvQBI8t2oEGb3EFfa1bccOjEHeCOMzMvZDhg66mBT5k3jUB5nGPxT/dIazmX0bWqGZ3trUAij/51PSdQDnv6iQ5Svs3fJE70NVpZYuPWItiYnheRlM4LP9YcqrhSwK/wAkfByBplXyObtO0MKq2xsxQ6HiRsqXXLfVie9liTTIdwr4ElYfK0TzL71fNNNvkNYKRR3kOprII7RRtAqqWmQuPnaGerPQdwXOhWKVsRbeEp1njtDmNx3alEZGy0aKo0KuLYs30NBL+fQJXEupkABQUTfO2b7FF7ERR5XkuzaCh3+j9oFT4wgMEIjtFaFXYKzJFtZqgFak00qZz6wZ1mgDsjC5KGKxDMvtRdCJBm5p2P2WMEHss/1B4zDcB0n0w/zNedTcohqyh/shUozYtcCOwSejLaBfCqNgD79LzyOS3pLvGG+rfmOpT5p6cjufgqfAT3ofZWFkaOebCAs74OX2+/LOaBla0JifPF2vZQCQ3SQtfOEjA9belQF0tPnhPjzsYhhyE2R45CrH/iLN1c9jd+qAvGqeH4D8JT/zlCKj6Uevlq9C1jqgT
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
