---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCO9ExvAQNDMxkmWPo134egLiF7yrar8tmTrm0G5c5cWwV0SJjO4s366I/F5Pro+FUXf4wFnIbM/pXqdlObeY9NKb+s5/JFGX72796MVAoRcIRzWK4nKR1ooJD0odR2pbONcWzgkk1LALQzGrPW6bjEcm29Tnkl4HK5mmHvl+3hfrohjNWtsqT3am46Dfv5XMP7f7hCMKB1mjfhdOt23wHaPypDXH8thirSahrOt/WABhMwJxqp1EWuD9M972NH1vRE5DGAhCxNCKrqPeXdxCgNUqpz9z2miuEic/6JNVCaHwFanQColsMObSjWt53LowCbHyQKduLvshdGt8+yV6M3UVdAyp9oGxCcYE3Ur02nVkq9G+s7xzwcwtsXnIpVXEobXfgaYZc2vRKcWTBRDTLevNvPf316M8UT48Pv6aOhm8Fjt7dHI47uE4rRWUC5iMRRNsREeyEhkfVswIqMe6htFcU7bVoDxKAsSBfIWlMwQdhTslx96YKiJWFmSRcOmcjHJzyZhmdshaG6e1NC8m/BGMSfKJBGF7OGeOyFwYsXVHFHRa617HpG3ARnD/ipKyhhxMw8a71dBPB4bfNLKEHhFq1zHquOFl/3YgUXHig85LDqoss+KHlnvNvfZPLkRF08Z7ZqRGM96wiiRsQvM41i2+6gIaKPA53+vft93SxSqoLG0o2jjQwvs1jm/kj2EYxlMZ7cZkeFTdDHnOy7HEhfI+dzWIr3mFqGgxNB8bDgVsr3LGyfljrH
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
