---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCSoA38pkjiLIj6I33+QiDq067Vv/+jA5trdnTN9YyoxGXqIIQzjz3et0uvY5OuBoczfNySTbSjselZuQc5ZJmodj9fdx7te1SVPx5viPwOEHOMKAGUwcSBFEjJMIz6BzJVp4Yr51azJUubK4Cm5SaVIDFY5iWK6Io2DgQEFNoMfMTO8KFrM5qbSRQWgNiXJFEufHbxDxGD4gAy0ZRleeeNDm/Ht468KdJS5Tnbct4OskEaZuEA6IdENCyREgXbu1AXQOF9oD+R5RECjUMAhuL4sCnVr+jNmWCtl0PNkqE1byfDgRSOluveyNy1bhhOHYuVvIBldcb/vVcYkTLgEHoy6cVkjBrRSR1b7f8KSbvesIS5VmsSIergJOIcxnvTH84IbtM9mflQLwoW9cQtLsdg4n0TmxPvMM7QNet5L4LC7W8T8v1ZThCitGOk5HQuGfthScYBsFWYec69/0xVczzEzFjP1DyQvNgcaFdDZ8N+8+e5RP7plk64zyHK8yQL3uUuQsIOriUDkv7nJOzX9/nQj8i8TRkI/gfIzIzUxbkhxgNHQVgbUeyEhLOM3MKI3zdd6lWESLD1wKy/yjsPVZnwmXnln7Xzb052FhyIcVC/3bpQcAYhFGHUaBHa1yOddRuar5gOP+QFunAXCtCZr6Lfz4TrghNQl0jQBXWYFcMwQ6e4RVKV/uHEoB8PEOfdiK1W9xr2b2T/FKW3+HICfl2UnyLkuhF+lmR4rM04kB9NPoy+TsL0AUml
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
