---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-token-secret
spec:
  encryptedData:
    api-token: AgAVYJua+T/269X2bgZeUXTXQHjsFc649m8gtsk6RRRs09hKlUU/xMwSEgiF8VZwuAakqOhLpLZBRkbnamcbWp6pmCHbLa4hO7kJMWE4Tyj4ZTiVrVwFdcYaarOXt1Aza7NG5jYWWebhxPFz9lwsIwqLL7CIJEr/p47JDtuikES03mODxLcuhhFU/RDdey1iKzE0sgyQRKlujCMLpfKzqaPE2XSNEDenHstg++ejmfSxPxdKhgVYzX0xr0QIeeGXRjBaZ4LJZQzyt9q+GSJ4rPTXRq2UraP8+qE61vdzto5SRAPP7GUNolXH6Ux9Bo3/SQCQ0PKJ2WohEHCTLhsaUZA4KZIEmTRygX0cz0T4roV5nEBG7InOdus+lYHNcMTcj6o71T80Xatg/1VeXCqXFNLSIRaszBq+qeDO8fz17opJ7JsVlkidl2EhfdzZfY+zaVm+8b3hZXjKMxuQMLwfmc0VfGYrhnM3iEV6z6QCUswyiflY+RBHp7Pxz0uEtVRYlZ8Y8JGVwlMApN3EJZwTgu82quIzB1kWMbPlXEXXg+ZwI7OR6fnX2EswltWYVF6ULnFAS9s/Mg1I4S6LVAQz9ell5G/gvDO4/uLvgrQARHoEp/Tk81QuR1RX86hZwTG+nNkbb40EkaWTO70tvmmdANwLjYEuCPp8UmACHClWBBGNZshJdoluTMqDUSYLBKvVuB0oCyDQz87PFM1r6sra54t6SCsTC4bUVP9/fd880yVY2VurXslbvME1d8mLlPuhaOi3PpoeAg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-token-secret
    type: Opaque
