---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-token-secret
spec:
  encryptedData:
    api-token: AgBsrSnWmMSl6HJ/K5DLkfh+hr6TSglDlqygVOb0FK+TsP6hYAcZNGK6q90FjWhBiEpzsLBYTaJ34jOwoJuv0j63jzspBD6kPv1ymnCZaNxVtv5QMaFUT4rH517puuXsBsPktwIPtoHFz6S7iqSHRnHsxML5EHtcUNxaR7a9t01Mb5k6oDf5gkqt0uG+X7reHOAqEi2LU3HFxEFt+HTQSGo6thNDfo51Seilck0lw8nQjN2c/uyr/4u0zVCKJJ64CzouxbYOSfW9AQ+6qXJWCOVs9MN5I9hUoc88XfTr9DnBJdaQ1GQeLlXkxkkQZyQw6k5BvbYgHS4B2H2wzO1DmVOfilhE//5htX68plNSQsWutOJBOTODPzvgGeRWw1fXRpdc5kpogT6GWEtqZYfPmOfe6Ax7vXofJiXkq/ocOBvqnVoO0IZY3aZP275o8htEVii62SOeZmXL0mlOngLXdtn5YYQ6m4RdvHt/BsiUVvlykiLTjvcRUFRGCqkhLSUKys79r4+opb2+QnXSr1M2thaBaIXpjLk+am1h1Iu9xVB/kzfUnK+B8ha6ycjofZzw/FW48bPygkSBX5y1lh/ZZ61+9u1YQmVymUcEUE2U4wKEP4PtrDYbXrbLKOUcVnICA65NGrwD/YB8LrnTHv0W9/36AATK5JWtN/SOHZsKQHW5bdyZaoWGLndNtyPC4+1+NeMjXZb1hSty5EW2Yx2G0HK+WwkORAcjVHrBFoDuPYE6Eoqo9d0Vv6eA
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-token-secret
    type: Opaque
