---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAm6PqD0LUrEcClh7MdJLtrKNmRbefQZVTtqSqA21989/Ud0uejlRRhiTejKwBfPfG5oxQZi1rUP/Ttd6POg2Xjsy9hqy8hsaIGsYjJYGd2EzAfPO/P3dT22hhircpBfPR5KBaHuP67T1d9j7GygPbC/pQzBZr59vFNMYUGjZtWeFf3RIoQ5WykObE3vd06lF4JocVMca1mS33/BxGGOHWxObWLDdE7jjiDJiwxnnqkHBvezGk+XyaSsv+OeyWIbkORvnMHqTh8WoQ1w9N1mZUoKPWQ7n3Qe3Uu/ZlfbM5Zc0wYw9nn1ajf5714suAdgjAws9ERwVUkyrpRSigT1j00yoEUhZuAM9PGs0Af3TQu/NU4KIKmbbidzha3Gq4WH4w4Q97dwF53/T6zvJzS0ByBQSc8uWr72+OFJg2/7Flqnr+65kRyTLcnWcwHUMA54dnmjv1ZFp4NTqmMupdhd5oujNIBeo31WYduR2vpfsSuvuQMYPPA3LIY9TlmN49Ra/CwrzwoCD+IE2yLavv6Yy5uH4ER78Wxx/jql6DqUnWJtl3p9s5pCBpRtLfkFMt7menp3ram1JKymcyxa+liJY2smOfPHWcmtVmb6Uau/LBLWd0eH5YEyNFj1KiCKs+34vGJD/gEoQOri6LRTxdcCOyIeLEddqZT8MivsnvyFOT3lCleMSv0QbTkg3fZbuV0TOGkyy+r8D9Rr5CF8vTDxFC7dbIYJxqAMdjyK97H9ldIQMQahXgWCuXa
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
