---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgALmth9nClTaEbFLqj8OaL5Z5ltw1N4rGAlzsp9y/XE2tROop0LTvUpW851w+xY7u4Eg3PFF5TtilCwsRpusjVFYUcQLHT7fgESMTspn7ljtd6BpzveUeewaElLXNe+Fu/L62p3LVGPnkoFgtxqLs9y6gS/Z7SeMyW55BtSXlcdjU8BAKfRxSu4XxaLthTIup7aeW0FUlOwBfYSrqXCVRAhkaxQr+NNX63Vobwips5AB+pIZ4+gUUKLAofHU99wjhIoFvxp/8dsVZTkojks4Kx3lSrNDlZ78bcqxVlPfmM8OTImrYSal81obBwFHloz/SBV1He5rEGe1khaeZYSDi339+FZ6oOInPQ916gkFxAKnfqekvO+tjskQjoL1FbIPu8h2QkHWUcba/GtUOMwtOY3Q93vp0lDDVu1ZMi4qIiyAfwj5B8lT6Nn4eoznEcMgpp5nvvol/asJ6+VZrj7XyzslW2/x2BNc9EojsLK5KhBdDv0lQS8fYhC2k8ionrbKYeae8dsVqsD37z2AKRPRE7lXM/hZS1wlPk0Otsz/B1sxkmP2B+VI73ywcvDoIyeol8DmM143L1EM1azu7lHpDv9GBtu8k/i3DZABRwzXNFwb2qnwHm90ci09NteRV1h/HCcuqFj2A4m94bR2J8PTjpDzJ5gmWIPquCIgsS4b79tYwye7mowIUTIXwsObAsc+CPt3d1VmI+BIEMTPMBJEUt0RCXcRiUDTWt4BppPRKxEji4qOv+NcEQV
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
