apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg

resources:
  - cluster.yaml
  - memos-db-secret-sealed.yaml
  - ../../../../base/cnpg-db/

patches:
  - target:
      group: cilium.io
      version: v2
      kind: CiliumNetworkPolicy
      name: default-database-netpol
    patch: |-
      - op: replace
        path: /metadata/name
        value: memos-database-netpol
      - op: replace
        path: /spec/endpointSelector/matchLabels/cnpg.io~1cluster
        value: memos-database-v1
      - op: replace
        path: /spec/egress/0/toEndpoints/0/matchLabels/cnpg.io~1cluster
        value: memos-database-v1
      - op: replace
        path: /spec/ingress/0/fromEndpoints/0/matchLabels/app
        value: memos
      - op: replace
        path: /spec/ingress/0/fromEndpoints/0/matchLabels/k8s:io.kubernetes.pod.namespace
        value: memos
      - op: replace
        path: /spec/ingress/1/fromEndpoints/0/matchLabels/cnpg.io~1cluster
        value: memos-database-v1
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: ScheduledBackup
      name: default-scheduled-backup
    patch: |-
      - op: replace
        path: /metadata/name
        value: memos-db-backup
      - op: replace
        path: /spec/cluster/name
        value: memos-database-v1
      - op: replace
        path: /spec/schedule
        value: '0 0 2 */2 * *'       # Every 2 days at 2:00 AM