---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: memos-db-creds
spec:
  encryptedData:
    password: AgCG2Ml25p+50A+C63jmyBVbNs6zGczwOnRconOuLwDIIv7Ol9pjkAmNL2Fb7gmttJZwBJ7Y3y/OEWMJgCHDjBqif+XY0W7irxgGiXXsC5Q4HeuoQbU4Ix0ZcduxW82SppMu8IAbjoYIUltA5jMfao6dk4+UHHlIEFCeBlZDPZhDNy/henzc1FV/q+6SrzvaRh3ITCnoXCB7xbXQHpOzTOoeELRQSUlXLKyVjgRZDs+QEM4Ji6eGIdfIgVE6JkbL/BvMUfQCL+pSuUXbx2x25CD3gz5dJMX2ZS9sqhq0qSPImCENvD9Wa9nbisrYG2TM2b1BtUfphBkpmnb+ib0FF5IEFTq19PaFvNvtA0W8iy9trGPvKa5hhD0WODyYgenDoiN8O5P8MD3rDyfMNL+09Y0/en2UWUZe5Yv26SYIirXHvO0Lc0cUU5AMfpVXnSpKXOJ3npX+bv4P4OSB8zGw5gZfU3eQ7Mw9asi1nmCVG+ugts0SbFkPZfevd1YOJoSAGzEXxB6L+d5bhYh6vAwy3w2VnhuBb/nE0OMvbRw2gInGOUw2hNPATAtLMD020y5Rg5bXp0wgkSFg98JDtLHeJ+pzuLGJl77njutrBXzjE01MiAIy8KlGW2hc/9K7vTOxH9YfOuJSGv5BpVDsxNwQr9xVI/vSSE4O2w5rod2GzspakbV7Nk6NPJ9C0MIUg9I+4uX8639AcjMdk9YLhBXdRhL5uGGe813m6ZUhuBNotlK24g==
    username: AgBiwi3/gOspYpt4Wz3XneFsRA3CIx3hga0/ZsRPYchwVA9nFXrmPw0UtLKIjCtWuGuQIsoFqOfZlzpp04fhG+AI6/sXuQnAa6aX6nSxbzcYOe4J2nJGeWoyZG+EY4wTeLMvluHLrL0PFG8PHLTWgrQpx+dJXpwGDHTDEYaSZoY3XxPPmm04PO1W+65ZBSSvUGoar8SzAMvWfCu3iKdp4+Ccwu3HoXzK1fUCO16Sm7AXazj7lATeNfI1DW5W3pb097uRoWngRBCjNvxc39aol6LUyupvdWX6rpkKSTzxbwDJfQHFZt1ZcQR6g2zYY7AUhF6ZilhQv5VXBlUr91FS8Y9kwAZ7yHOCzZF5HAdpsBY5c9riEjktN6u7hoV8SqOOia8jf6cy6TvLPppDfVEXHPkZ0HvIN8gAaTaStwNXDWZd+Z6Q4d6PmE8J/Jl4RL2uE3rSWO4C1Vc2zzAKtCc+v6T8FSbl/e/cipbv3RUAq9kQQskqPzMnH279a2zEU7zGI7iFLNqeotOArZaeJgoUvI/J9QLzFLlEHk/9daQaP8tLh4VwPd0WvOMgL3N7xiunqiWVvJKQdhPxgWKgaFIDGhEt5UMxd3/eh1hItThi5K25edqhf/0Pky5QMFFKmUAIocU61dgVZCPTcVZToWbXZTv7TQ0rlvbtGnySubMrdsfGgWVCf61xO8kPmfYbK8w7LP1XfgelMw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        cnpg.io/reload: "true"
      name: memos-db-creds
    type: kubernetes.io/basic-auth
