---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: memos-db-creds
spec:
  encryptedData:
    password: AgBJKAGMycP9DVND3VAMrhiCepv2iID0b71/GVbk9EYXPKVl13iQcUuwuAW+17NX25Sa00iTKccd0X0XA08OQe6c6DiZ1AEbEgPUhR47pwYf8hY22yf1gatCZSYDz1txWE0IL/SGYKuaeGG+TpN2eiX6VJDSGKY+9RyWigGHDlMXXezRotCG6EquKUTFugyeGaYUygBLSCdlnYIjk3hYxeqPX0Qgl2VRmcBtF5RUtNcd4S4kg3/iWaqoxHUH3IcK68cP0c9RQG5NlUVb9QC9Z6uM9515u7gvgv7zEoBlVHMbc21YIRcfBHwqD8c/VCrn79QIiuRSXIEIl0k6vCBREgnk/yEBzbRrRjs/oNJLgT9vfcRdBYQssNbPy5RZfzOjnMwao1UqBIvS2eQa0jUpQVe8NHa/B8yvBO7uQTq/SbD23knn3HAWpm4r/g9FtG1z6GytgU4vWbrmll9vm4xjljxFiG8Vp+ndRy/Zpjoh1X+lP4McnbxCFIWQ2ZCSz+bCVCqZ96+E3TkH90QvnwGGHqy1ucbZRfVCHrW029vtLd0f1q26jRZ6oYCyuqGrz2LirUg+0yUzbafRikGvjrbjzSl/ye85NVLJgUzihooiSBfh6XixLuR0QKmV8letBfxiR+jZYodM1YtA6vKq++YGyNZO8J8vfDt+D/+SiQ4czx4xJh41FnAJlYAXQ5XdstJSR4lNX1iucWcqW3rFXnvxqF/eWU/mqcs0vEhwYLCD/UnHDQ==
    username: AgAY5BNhmx9ciCxdA6p1I30uEez6x3U3xxy4Eb6/yOrxFN9UTjj8bsCEKFhv/VNk2qj1HQDKb4AG70geo++Josotg8U1d/ziywu26M3WhJqUXZCHpgHyg+Otjam7zyVrj37E1Tbe+SED3/Vkz16eBXSXq5hXTNfBam6oY2RoyuyhH6cb+HKcM2TcETzURXaUKuM08D/sfcITOvu0hJLHzhb7SuRxg+/Yg3LkUbStzu5PTMBwI9UZunvMz0ux2H7VsdQRPBYwuQr8raImSlgdDOU/Q7sbq/UGZo8hmwTXHC+X4FMa1suBsnRoq/ktU1YxQt6CXeEINlLCY+1tNdvBHSpdS0UjqHiV+toSih/ZShx8hoZUKjEVmmONT7lfofZJj4qAV6frLMqi8YAxvtzxG7FKg9x01nh7nZ6y933/um3bdWuAET86dArCRikYRDOEMUYHtr1FJJesBZ87bk08CfiNyD2O15X1Isx5GyfkFTXKZW5Hl+wmNgiKG/jbZk85qDhaWAF5TsVh8e3dSib0GVtTpazRVuIC9HKnucBbt+C18bu1bKWBjRsVcmOrcsuWwkldFzYUrwAw74mf6kCSUWgTM+NrQijl8cP1Xp6BLn4SEzt4+1eYM0Ub5kL1HY2J9u/S/ymShZ4h+fcbPiNmY6nK82woU16qHqMQxsuUS6nf/oS+uz/Oh49laYqWsT7GNSUjIuaH+g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        cnpg.io/reload: "true"
      name: memos-db-creds
    type: kubernetes.io/basic-auth
