apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - namespace.yaml
  - vault-init-job.yaml
  - vault-unseal-job.yaml
  - http-route.yaml
helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.28.0
    releaseName: vault
    valuesFile: values.yaml
    includeCRDs: true