apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: vault-init
          image: hashicorp/vault:1.19.0
          command:
            - /bin/sh
            - -c
            - |
              export VAULT_ADDR="http://vault.vault.svc.cluster.local:8200"

              echo "Waiting for Vault to be ready..."
              until vault status; do sleep 2; done

              if vault status | grep 'Initialized.*true'; then
                echo "Vault already initialized, exiting..."
                exit 0
              fi

              echo "Initializing Vault..."
              vault operator init -key-shares=3 -key-threshold=2 -format=json > /tmp/init.json

              echo "Saving unseal keys and root token to Kubernetes Secret..."
              kubectl -n vault create secret generic vault-unseal-keys \
                --from-literal=unseal-key-1="$(jq -r '.unseal_keys_b64[0]' /tmp/init.json)" \
                --from-literal=unseal-key-2="$(jq -r '.unseal_keys_b64[1]' /tmp/init.json)" \
                --from-literal=unseal-key-3="$(jq -r '.unseal_keys_b64[2]' /tmp/init.json)" \
                --from-literal=root-token="$(jq -r '.root_token' /tmp/init.json)"

              echo "Vault initialized and keys stored in vault-unseal-keys secret"
          env:
            - name: VAULT_ADDR
              value: http://vault.vault.svc.cluster.local:8200