apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-unseal
  namespace: vault
spec:
  schedule: "*/1 * * * *"  # runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: vault-unseal
              image: hashicorp/vault:1.16.1
              command:
                - /bin/sh
                - -c
                - |
                  export VAULT_ADDR="http://vault.vault.svc.cluster.local:8200"

                  echo "Checking Vault seal status..."
                  sealed=$(vault status -format=json | jq -r '.sealed')

                  if [ "$sealed" = "false" ]; then
                    echo "Vault is already unsealed, exiting..."
                    exit 0
                  fi

                  echo "Vault is sealed, unsealing now..."

                  # Read unseal keys from the Kubernetes secret
                  UNSEAL_KEY_1=$(kubectl get secret vault-unseal-keys -n vault -o jsonpath='{.data.unseal-key-1}' | base64 --decode)
                  UNSEAL_KEY_2=$(kubectl get secret vault-unseal-keys -n vault -o jsonpath='{.data.unseal-key-2}' | base64 --decode)
                  UNSEAL_KEY_3=$(kubectl get secret vault-unseal-keys -n vault -o jsonpath='{.data.unseal-key-3}' | base64 --decode)
                  # Use two keys as threshold is 2
                  vault operator unseal "$UNSEAL_KEY_1"
                  vault operator unseal "$UNSEAL_KEY_2"
                  vault operator unseal "$UNSEAL_KEY_3"

                  echo "Vault unsealed."