---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: renovate-secret
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgBLgp2T0YOmTfEPzaK2kmisamgb498he822Wfu9RxsILNaaZ6rQHyjSgQa5QJK/AFWA2lP+triRkn71IaYkWc2bPYDu+NvHJgCSpdoXr+zU1E0eAYLk7npO58LY7p1+Y27FhwMMEM0QUiaHRvuz6A4R48DpAv99C+yQnQeqiRn1DFHNHMVA9fpboKTi98keuZOF3EAAA8A+lCl51EmvqvXn8ZerCYUnmXmbrIE+BYEbXwtj2Fej5Z3FDkj7cLDb8+sM4OJA6UNNVnJdHJE9SDWzx6rhO7OvESQ2Tc0LPonNxEynR6zpmOSxXUSnUJJPNhGGB8Yw4WoN8AtNiLK+ClYsbsY4hpkjkv7Y3+MR/2HpWo/w3ULb3DJ4c/vNH9UjjHiOkHYuK5YxRHJtI6c3EzHVWJQIqn2H+faXc2Cnw5AZw8ot3mGPRDgu02Gy8XA1+8Lo/8qJgVuNSWNyNKAap2Pzm0/1CsIOQ6mLkejRmGfn2VBebnsOO+iBcRwJx07rY4O/P6V5vTrBO3T9B/FZSg0ghfsT1PU9zVS58jWi/4YB+/BB34fjsdBZyw+r1Bc0C6WMEDqQwr47KtOIzOkLzp2w8O54KZr4WdndxGXJYJosSQpJcMOu/UALW7RFkH5tFPvAFidueZHsR18I6j56szyHnHcsurVNxFHT/b6nn4YeMYGJQNUk1+5bo0vykmJYx0DJtMulQ09a1b1pBVS9nu1I3CV3l4qgl0GYX3xf14beltI508XmjWS3k7hNchbMNjh7w40cuz47gGkPX8ZfaD1VU9hfn0ce9WSJSu1PubUVaLkknUiEcxR5zXiRBEI=
    RENOVATE_TOKEN: AgBWhqSKz4PTxDAIGTz4lj7Uod3/ugz6m8sfYbcf6th5mFtutnDSR+p1v7vK4o2f+MUDRipI6iszQL2OShBZDRTW7ZaGb0JmAklS5e9UOJDpuEj7Hkjkoi2BoBCam1LcjZdisR69Yb7KGxRS63ZPy/65Go+qRzXhdfYizInVzvErLFe3IzjmJRmPrBlw9fb/J/ki509N8pjFwY2g0LGNEvb7w4L1YQ08OaSgXCnArenjiZHw1MaHZKN44/VzHuW1Sw4iq79bEdHSxQVXkSTnL9R2GjfE0iRbxr/FTl7xRyNoO69PYdmb6Ns7F5uUkGJILhqFLg7XTs5npZiCFu547gSKWj1t8XMnuxUybJ6NENkImeUPTBsTXbBIjnaWgFYMtDOoNUqOxaYEx4U6ms40up97kiqShUh8SEt5NSFI9shTkKL677FfrUuEtF82qQv5NFGtj/Soxr34hH3suPzWuKE9GRHzXjOr0wTtgpFrxIHbToQGZ8RcOO7/L+fF3t+Jos+2pB1/gP5waLbZM5dIQXxHFlOzXd8wHegDN/ACqP/8hPqzhAzi63vfpvixktPsWpvajRlJs7IE4K6p1h14jZB1+R3zwrYxiL7KX979rW5fKwU9BCC+ELAEjKvkS31R3fRy7k2C4nzt87M7f1yDhoVnPqSuNNMJX3K54uaEYNLmRyj2tq5JtGzvNeYJES9TOKW195/tarS0jZnhltyGEnk0GbNl6knFyIneb1+NTMme2i9BpzciFIwBdu466b+iPOxiWltSTbQVr18ZdDvJ7OMa3zTb02B5igwXvHF0jpMJgSi4hDSZVhYsMRiuthw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: renovate-secret
