apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: renovate-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: prod/controllers/renovate
        property: RENOVATE_TOKEN
    - secretKey: RENOVATE_PLATFORM
      remoteRef:
        key: prod/controllers/renovate
        property: RENOVATE_PLATFORM