---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: renovate-secret
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgAyKtr/u93orw2+E36wpJNBLMrTEq+/uB5EXDC9GZvmuyhj6sp7RKjgL+9Iu1ANr266kDIt697YmAELho1FeUSzUFcGbT/J6AbCaVtM/1HzWAzFCCPrMvp7QXaIqs1Q0i21oYzPMVL5WEJEt4vMVSyCm3Ly2W8L1pwdyqeVOccMd/8A18ZdKLDPmZMtzJby1HicdxLt+mL1qZ+rW/LM1oikSq8Viu7etQuzjfVOZPB3KQVx5APNip3jSV323VKmDKLil3DKGjpZoEy4j+lKcNZbMd7qeSKAIC8HmebCahHjFquGPqug7qIQBgROMPt+1Jhm3kGmykX0XIEEcgyFN4bJVdgc5wxVYzYLl7JuMePyblxRlqhPQ2olqmuF1gxi4X/dO6ohiJA4b03U+XBv4RcGXbrqaYmU9E/lrunosDtoKk2STdVQ7eGxttXODDhm+mKxlSmipgLpABQhu4lTeB1rdL/SxVFH+WoEod5rNPaI4k+b2R5zJRzNSi+dhAan9FDzrHCPcQlcWvxg0On714RpeQOXRZfepRDZw14xKHB70cf67oBgGNV3QI1VTp8bAvomVsKEC0mbIWxe1bgIRB7LkVWL9viCXg4j7Mi0SxkqcnRmJ0LS/jbhj9qftG993C8y7assXAoKgEjBh5EpUZlAfBCcyMH9q1vKNMPVDxvGJ/4Zr62np9qCEBxMOGVRsl1Ocp41LkqLRnOoUFTzar6mBOVg0gpJsiRdGUC+0+WM2m6Q8fZ7MH3V42ikXa0Hq7O+jSw/SXN0CDKaba9W/rhPtWNRjhVU0X/WTOyf8KefcnHhx9CjLzAXPN5vsVI=
    RENOVATE_TOKEN: AgAyKtr/u93orw2+E36wpJNBLMrTEq+/uB5EXDC9GZvmuyhj6sp7RKjgL+9Iu1ANr266kDIt697YmAELho1FeUSzUFcGbT/J6AbCaVtM/1HzWAzFCCPrMvp7QXaIqs1Q0i21oYzPMVL5WEJEt4vMVSyCm3Ly2W8L1pwdyqeVOccMd/8A18ZdKLDPmZMtzJby1HicdxLt+mL1qZ+rW/LM1oikSq8Viu7etQuzjfVOZPB3KQVx5APNip3jSV323VKmDKLil3DKGjpZoEy4j+lKcNZbMd7qeSKAIC8HmebCahHjFquGPqug7qIQBgROMPt+1Jhm3kGmykX0XIEEcgyFN4bJVdgc5wxVYzYLl7JuMePyblxRlqhPQ2olqmuF1gxi4X/dO6ohiJA4b03U+XBv4RcGXbrqaYmU9E/lrunosDtoKk2STdVQ7eGxttXODDhm+mKxlSmipgLpABQhu4lTeB1rdL/SxVFH+WoEod5rNPaI4k+b2R5zJRzNSi+dhAan9FDzrHCPcQlcWvxg0On714RpeQOXRZfepRDZw14xKHB70cf67oBgGNV3QI1VTp8bAvomVsKEC0mbIWxe1bgIRB7LkVWL9viCXg4j7Mi0SxkqcnRmJ0LS/jbhj9qftG993C8y7assXAoKgEjBh5EpUZlAfBCcyMH9q1vKNMPVDxvGJ/4Zr62np9qCEBxMOGVRsl1Ocp41LkqLRnOoUFTzar6mBOVg0gpJsiRdGUC+0+WM2m6Q8fZ7MH3V42ikXa0Hq7O+jSw/SXN0CDKaba9W/rhPtWNRjhVU0X/WTOyf8KefcnHhx9CjLzAXPN5vsVI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: renovate-secret
