apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
  labels:
    app: chrome
    tier: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
      tier: crawler
  template:
    metadata:
      labels:
        app: chrome
        tier: crawler
        netpol.cilium.io/egress-to-intra: "true"
        netpol.cilium.io/egress-to-kube-dns: "true"
        netpol.cilium.io/egress-to-public-ips: "true"
        netpol.cilium.io/ingress-from-intra: "true"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: chrome
          image: ghcr.io/karakeep-app/karakeep-chrome:151.0.7922.47-r1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9222
              name: http
          args:
            - --disable-gpu
            - --disable-dev-shm-usage
            - --hide-scrollbars
            - --disable-blink-features=AutomationControlled
            - --window-size=1440,900
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: cache
              mountPath: /.cache
      volumes:
        - name: cache
          emptyDir: {}