apiVersion: v1
kind: Service
metadata:
  name: chrome
  labels:
    app: chrome
    tier: crawler
spec:
  selector:
    app: chrome
    tier: crawler
  ports:
    - name: http
      port: 9222
      protocol: TCP
      targetPort: http
  type: ClusterIP