apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: arc-controller
  labels:
    release: kube-prometheus-stack
    prometheus: kube-prometheus-stack-prometheus
spec:
  namespaceSelector:
    matchNames:
      - arc
  selector:
    matchLabels:
      app.kubernetes.io/instance: arc
      app.kubernetes.io/name: arc-controller
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s