apiVersion: v1
kind: Service
metadata:
  name: meilisearch-headless
  labels:
    app: meilisearch
    tier: search-engine
spec:
  clusterIP: None
  selector:
    app: meilisearch
    tier: search-engine
  ports:
    - port: 7700
      name: http