apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meilisearch
  labels:
    app: meilisearch
spec:
  serviceName: meilisearch-headless
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.36.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7700
              name: meilisearch-pod
          readinessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 15
            periodSeconds: 30
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
          volumeMounts:
            - name: meilisearch-data
              mountPath: /meili_data
          envFrom:
            - secretRef:
                name: karakeep-secret
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
  volumeClaimTemplates:
    - metadata:
        name: meilisearch-data
        labels:
          recurring-job.longhorn.io/source: enabled
          recurring-job-group.longhorn.io/standard: enabled
          recurring-job-group.longhorn.io/default: disabled
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
