apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-pvc
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/important: enabled
    recurring-job-group.longhorn.io/default: disabled
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn