apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  blocks:
    - cidr: "192.168.1.32/29"  # Usable IPs: 192.168.101.34 to 192.168.101.37
  allowFirstLastIPs: "No"  # Required in Cilium 1.16+ if reserving first/last IPs
  # Announce for all LoadBalancer services
  serviceSelector:
    matchLabels: {}
