apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: main-l2-policy
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  interfaces:
    - 'e*'
  loadBalancerIPs: true

  # Announce for all LoadBalancer services
  serviceSelector:
    matchLabels: {}