apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: control-plane-vip-pool
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.1.26"
      stop: "192.168.1.26"
  serviceSelector:
    matchLabels:
      app: kube-apiserver-vip