---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgBLANMQtV+ce2gOUdApu/6zBQRpvSAnnSzFqZ2cgpa7cS3x3iyPnF8L1HE1fNqn8NMwJJjWHLcno8LGdWNwEPVgsXi0qaHeB8CrENkw8+2ZIsFyWYwW6+aDSpGQtygYYHcuzTxRVFJHp+MsptN2KSQ3Bcsj8p0nBDglxPx3qYusOfniVUAaOd3QbIs59MPIt+6EC2sHp56Fr5r57kbTC8iHM5WFUTX6Y930YPp5aWmnBPtcTlgBNJ2ihAzZDRJH+0GBg1u+XYdhuoOIiPEmNTbCwSKZuUwD89ATMfsMG6EEt5AxswqIXGZ+VSh8Rlr+I6Vj+4loYzWM/EwdPyswPSvNoyEA5tNlOi6WFGimHEHn/69z3cJe46gkqT/Inm/UKZIT3aTJRRrUyw3FYHlssM0u7sV83u03UQHEknDsjT+Y3RkkDONEt7I7RYu6e9I3aBSdbKLjmDJTJreWtSubO93wXNT0xI/NgbzJcluILKLfNF0F4cDcXSBb+9pj9KLCbX6mWumlqJglu/E3yWlVmf1FjBWc1Sq3PH1CHuBeP73C31XWFrjtl64ZYCoQAd8iKxLNxNA/9msBrpxfWI60VdyTkeJI8XHfDLSWfGRrWMXRe3Q+pj/YJLhlsOurW/o9xMkbcnUdaWS23mVzQNky4NN1n/TmINFU3r+ht5jOW2wV6MvEO4lSbphVgtIzDfYMUHV9SYBaQ5aHe2g2FrbLAvextOxPZGHmaiiKNIA/Pe4xxYI24/dCq0jAEwKyd56IZwDrrqfSSw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-api-token-secret
    type: Opaque
