---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgA0ovQaMbtvn6fyUwOfqKgugJCx8PEtlvoxfqIpmsTOlY+1ubzkn4czQOjS0C0qHFnB6B2pV4ot2VfhirnIVsQbGvp8VtyVqgXktNKO0BUgpBjYmMerII2/qdseWhuWGOJ6qlUP/f61U0EsMl51h+bzv/fLW1nbJpRgFcWEruEKNjnL8Q7hk5SeA1fwwZLv7enf7eL6HnwBkcOMViOaAeyR5HtI6NKh+YnDVasChW6dGrEusBTmPiohbRF6dL0nyKMDEanPtMMQGHoAXwcfUbXPhXc8YJEEuRpP0141617Eqs95gEO2AUbcBBu5cXqGDldaKJa/J5k89CYmVr/xLW/Q9kXCeyjFBirF6ZiLnLCcJP7+nHhZCHXnqGiljRoilEX1r7GVamXRmubbDNpHTIVODGpMahk/cQfC1PEGGyWWVjzTF7Re22tJNsV7yiS3s+jhUOiqEBhURxnAZc0eSsl4jt42wv0vfXXq/TZ2+kE1OUcTocN7kO0VQlVCP6jrIewJfY765NG+JJ953p6r3CLKfRnBWGbDkke7ybpqzMv+NWWk+kYKb/77VVNmVxW3goNFwwWcp1qNWQRhFKfVO/73hR3mm3oGLxtO7xcTDifIpiyNkRXDkguQcQ/1RbFry50Q8Zad8EsPevyZ21HarSzt+B6EfpxJMrtdDWPK/E2LlYEdAyqtX1fFLXAHcBai26S7xSYv6GLHUtAp1BOMBovDDQGqJR9m8N6FLKscng46QDUeZPgfOxVM
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: external-dns
    type: Opaque
