---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-target-secret
  namespace: external-dns
spec:
  encryptedData:
    target: AgBJ+1SWaYTNsG3DWp80UdAJtQlC1wfK5NcDbe2Ag2W4fOvn1ArM//19VoV0pIqNssNZoC9xie/CaKOcYy2j8f0AmhKi+RM8IfqWUXhgCqUJ/o9U7pBtpH0R2mNZmB9eCNWsIx5J6apRf1UWUr8Sx3IGoP+5g2y6VBiTKwzG2bMNqjUdjD/nvDJQiWlvFy9c+h8VNK+9SzRrx6M2bMm8G37sPhsa5adYT+KGNZcOnTWplQ9E5V8EEhojEGzjjGsjxteXven1IJN8PDW21JwtqWQBUMEhAyjNV82N56ZTUmU2tTKUE2zwKfLvt1kDkjJTpic5b9vzqOlljkQgrE5Nh7SczyLi46lVV/534pFTf5Xk65nq6Hoe0UBsjdK15NVsQIhP7qZBGuBuOIZQRS3zWwzpzPDYoegjwjqnxaD5E9F0kXgW5ViW84rQoMAUz+QW2p0Un9JlncjnvtpW2STGgOLbUC/g9EEy6sowkGDVfs9JWdrsX7FKboHKbjgEatz3EwYnj8rPPx1QBc1z5IbVd52azDggJHhgMA/9T7f71wfaOdTNj9OTZfTvXCZv3z78jq6onydw16+a9PUXWibYvNgiyYLQWSaA1E/4X+trXNgytTBwqufZrs8cZ7VVgvOQd9ofGqP+BJYIeDsLrb7SFR+zhuKiZyAfDplM1FPQDYXOZAaffts4ZOOyyPOxyTH15BFtVlEGC4BYYMp4NS7UVEJD+0fKi9950/oFJ1zVn/dw4er5Aj0lr4Q/bx6hpPDVeOWaBadXYQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-target-secret
      namespace: external-dns
    type: Opaque
