---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgCJJZDTFzGgMKx2WD3Kmu585aATxJGqFpaLXsAzCvJ76UFwxdjCxHqWhBEaa5teGSa3BqA11rzZpO/ke/RwJwh+I1xzDIk+z+fq/8GLDCkmqGXD3jQ2Frj5P36Ckl12W1D0w/GNIpXLM115JzjDdQ7yRLxITK8JFcZQA2F4/DsZ8HsShK8+I+23Ez0jWV2pkpsjk8nVMebMbLqY6wQ2yUMULZqVn395L5TM/7WLoX3L1/Kr6nV+YB8Z8LKQFOIUa4LoezSF0aw9oVVjRhOmIeMEYllKkBYeWFC37cL+pemKXVEKRhcNP9jRUhtsn+CVs7gmKxYgpPh6I17GCpp+P9/JdxmuO5Up4yqyVTPzoASm3+WbCT89nyPHOs6MBVxqRcPAtSky9k6G5XAOuGBeZXRALA7LuPWc1OKrL0wwsIbNSffhCbxBtE5hW+UaZ9vTTC+SFZcMf5tPclx8HUBXwTQWuztYM1caFQVDKe2V6/M8W3b3ibCEIqWRZ+2ppihVEmmtQJHedbw/PhJwYBez0aCtaPpVaMfM04gTY5wOZCc10x/+vmRD6J3hfU/PbLmaVdvJjQWPMapUh0UHr+JWcTQDMJlcbKLib+VGTARlMt2UaozHEPA5jRUkWCoN+fwg5jc7cFxBheCN4GlfNVC1Uf2ssnGmFxmbGkJThWxu2awHphqpIm/FaOCehftIltTGLSpqX+EmTVhU58SXyMXq2i9s5Kl9TYoTyGefxvot1gzlGsubJzTMdBDA
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: external-dns
    type: Opaque
