---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgA0JKK9l1jg5jn1ytCTPGzUllVXKTWs5tvu61mk+iHdi2yIKNUhVAXfggthoblRo6RXkDxhgMdH7nChC/d1RgI33NcMfONFIkzM5HkS/g2bDCYWsE8zVLyxXsbNjk4KRtiYo/i+H876bPXqCF51FqRm/aaU9N6cF0EWU025pis2Rmtw5mVeDHped+ZIikFOBOEnD6apZi0c2kt60jyWiHMnCgighITGOceIaMavvVDkfOaPA8lb+3iImVenJ+SeO9hXlfThAuuQm3QYz0BD6x12LDl/XgSzli19DWO8AOCLmr2l5S0/IZOZZ0mvXn4AzLuxRgRg73PQzvr/bhN256XFxUrq+3ay8VZQsimnwADVHuu8nrLN2Ai6AsPSbhu0ANHI+5CPiyavPH4DfnCYqijJk+x6e/iFWcSlSizMBaG7fO2UkwoJAXiAxBMDL7r9Hn+zzF3fwGpELKaVMjSR8ogLNH6a6RA+SrK9CxnSh3OTutWL40J4PJd1Y21JyzhmtO3F4T792elhViu0Dhw7DEtKAJLyLELtDPzKJqnBXzDwdIX1f6NS4CwVDfKBo/FgRvpSxRYYkYqgHZrZAw/B7nHIAmQtSkhjhekjIWpA5ST1QMGe/nuaW1Egvekwzq3ksxAkyYCJ8L/vFSsyZQu6j8rD72cMI1Hi3aCxm7ugBXz2E3gatnrKmCbjuvGunHTWypgKZQVgKVmy78dZgd/jDLb3QixhI33y6YupF/aAtaFM4z09cSAvqtcl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
    type: Opaque
