apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: external-dns-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: prod/networking/external-dns
        property: api-token