---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-secrets
  namespace: prometheus-stack
spec:
  encryptedData:
    telegram-bot-token: AgAZzIabHeqfE88+Qt0L1mn+f7zm13U6BPcSHguElv6FhafsI1AzknyiDuyy9CZlcoSfDIl7ha9DEd6QMU1GB6sj0k07NwxUPaKlQHuh4mfEsil6POftA0jNTupV0cqOgtXdygzAxJyz/n6vKWxnYggLOhkM1fyImMu5aTPxpFNFayGIwwvb0ThmjasckvXgasuoCPdQLUNIEeEBws2bDiCqoZ9Ua8xP+z1JQfiAAQkv3GIBthUKHBZ7WliAADJyJ06HcmITqdaLjjCN1Y9hccvFWviRA9f5nTqSwNa5giLrvDelCSvn2If6VwI1VD0vXbeJTDPrygF1iUy+/euCST+4ThHBNztdcNRiPqtSJryU71RtYRUYXqGzzXDsEcDk4TeWYPS5jxy3nKZYfp9bQYZLfM3MkvHYaU72hlzU4Gq+rme0S/rXPgX9qNCbmZ091iMbC5tc0hTZEVCxdj/EppUWXYG0Bz9otTjRwDfrqX2BkMcTLiK5wFV+Zavsd/RH/Zp9GwFzVTKzJrp9vyZAKnuyNVMrNx44NgXKj3dDgEKL9jV9+cXwCLjXpIQlncRiXMVIYq/wtbrCC1L4Idojqo/d4v6HhHj7JW6bq0I9JCOOQdTRpZ7yrqZLf0tD7FBMglz4daXeQ2YIaKUI7i5G4Gtvke7A/t2JZrSs5V9iTzlinFULxlDFaP4O5Z+YyD43wtLXmvFujPAdaHKhl/4F/MXc2eRFoQKelS8lDts12zVjw1JrKX3ZH2qA34N8BQSB
    telegram-chat-id: AgDET4nZCIyMtqdtC/CfZmLf+TUC3V/tJgReHva6wmS0Ux0dso6/hg64leH8m6gMcSN0GiTZVYAPI9K8WPnTsOzVM4DQyG1iBjA4hVR7x/KgbjRc6Q1QUem3f4XlYuCx0TKXt6dl19Fwhf5KJq7PE9WMLzL+E+qaZBWJKyic79TqPp++K8zBC8hFBqFH67osc8+FY0W8dlZitnldNxjZOxkTIiry74iTdEENV/wQJNzSn7U3xMrEQAn2P64Y8uWtUyqVnyiv4Uvg0fZ+CGCqCuuzQF4WbeZbYck5X/7Qtd8efrSKVZ1iC5gUXazvbzWNsbNn/w+ylCeEzroJ19lYpjEw4CUIgBNLeJaEsYHfx6lGnuDtQD+YIDML0Ki6EgpvJ4deaVl3rGYzTu2S6VVGRQO0H0lxAa05U2iKMbhQ9hE//tstwJ1dmm1z/LshyWWMlKi2G+/MIl4XX5nQkoRFKEf8JQa6rUuii42zhIDGHsKptJ9JlizNzqBqK5qqfrVNjeRqDd6GXOjxoIiZ3hahcXdYDMtG8Avef0US2sOIPDcJZMT8flctwpCmwKSHz59/hM4Zx0IFZgT7GIdOyqc9xsD2qI0+n5ma2FRLo6Nm/c8c3eDgaL8XkPWRZN0r9+XNtJuNtD1czKq8BdX2gCXpbMry5w/Fd+8RadR29ejYuObmwKJTcgUTN7XFAnCiyjBiQPBJp1bgCSLkEnrL
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-secrets
      namespace: prometheus-stack
    type: Opaque
