---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: alertmanager-receivers-secret
spec:
  encryptedData:
    telegram-bot-token: AgBFo3dBeWmucluVTwQ8ki80VCb/CqbGUM3iRuRC93vrWa2CjYFIRw6Z2xLg2DugPP7KAGrUE49luzZmmCrP2W4sDoxF71s8y/mOMovXSoCIJ+nebgxdOhOZqrbAdVTWckYPJ1+6NjT0Qx49LpCDwR5QiFz0aIvp0c6lRcwgJpz7b215C5FzsU2dyb2MJeUpQ5sYIQuiM7Ao1Svm3Ox1q4boyGnI/UrfGpkGC4S+9cw4wByjZLPnqSxx+a0QwyP6FiznTuz6LUqYLCx4+lVGarHnDYh9O4ufhtfk1IsFmqpEAHlqi3FrTin3VWPMEi/j8eNBSNzcBf69ofwNBRAS1lunAZWVQVQ/tsJzsRFN9wR+cQqV5Bqu2TAJuD+LNlyjwOXauWiokdeXclsJolAL4J0paUyQ6whBp+iD+FX38dkY+yd+Lk0g1hggKxPaj3Sf+4HeZrenI96whUItzOphd8lWxpJhJy/or/KtHHWxqPTHnBrGoB3wBXrWcHLFm3FR27oX6RHdjSKfJDIHcL9EjhQIri5z717PcH52NHWzkcPK2MQsZE9/lJj3xZmUoW8G/+P0yazW4CTAf5wLZvt9N4gLtQ2/x7H3MqhG15uF7uRNzj9Zsu34BsysCz1/b7E/5K/BZT1FdZuX/KxqUWWi2Gt9nW2NKWV39akZSHk7T8Q6Mol6bAc42RxKlwS0k1vrVsnKn4Wo9lYfoFh8zggEmACM1Fa/Zbl3zXRxuZsOd3vp1dvlifyJ5/JEZ5VzNo1/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: alertmanager-receivers-secret
