apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: alertmanager-receivers-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: telegram-bot-token
      remoteRef:
        key: prod/monitor/alertmanager
        property: telegram-bot-token