---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-secrets
  namespace: prometheus-stack
spec:
  encryptedData:
    telegram-bot-token: AgAZzIabHeqfE88+Qt0L1mn+f7zm13U6BPcSHguElv6FhafsI1AzknyiDuyy9CZlcoSfDIl7ha9DEd6QMU1GB6sj0k07NwxUPaKlQHuh4mfEsil6POftA0jNTupV0cqOgtXdygzAxJyz/n6vKWxnYggLOhkM1fyImMu5aTPxpFNFayGIwwvb0ThmjasckvXgasuoCPdQLUNIEeEBws2bDiCqoZ9Ua8xP+z1JQfiAAQkv3GIBthUKHBZ7WliAADJyJ06HcmITqdaLjjCN1Y9hccvFWviRA9f5nTqSwNa5giLrvDelCSvn2If6VwI1VD0vXbeJTDPrygF1iUy+/euCST+4ThHBNztdcNRiPqtSJryU71RtYRUYXqGzzXDsEcDk4TeWYPS5jxy3nKZYfp9bQYZLfM3MkvHYaU72hlzU4Gq+rme0S/rXPgX9qNCbmZ091iMbC5tc0hTZEVCxdj/EppUWXYG0Bz9otTjRwDfrqX2BkMcTLiK5wFV+Zavsd/RH/Zp9GwFzVTKzJrp9vyZAKnuyNVMrNx44NgXKj3dDgEKL9jV9+cXwCLjXpIQlncRiXMVIYq/wtbrCC1L4Idojqo/d4v6HhHj7JW6bq0I9JCOOQdTRpZ7yrqZLf0tD7FBMglz4daXeQ2YIaKUI7i5G4Gtvke7A/t2JZrSs5V9iTzlinFULxlDFaP4O5Z+YyD43wtLXmvFujPAdaHKhl/4F/MXc2eRFoQKelS8lDts12zVjw1JrKX3ZH2qA34N8BQSB
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-secrets
      namespace: prometheus-stack
    type: Opaque
