apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: grafana-admin-user
      remoteRef:
        key: prod/monitor/grafana
        property: grafana-admin-user
    - secretKey: grafana-admin-password
      remoteRef:
        key: prod/monitor/grafana
        property: grafana-admin-password