---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: grafana-secrets
spec:
  encryptedData:
    grafana-admin-password: AgBzy7/hV3RpOpmplriMzLKD7vD36dVdoPpc2phiLlizD0oJP59O5Q0VJtNdvYa1+3TOp9cUz7sNm6dzA7q3P4qwdf6Iv2CjdxpeF2jW7PDw95ZOMhrgWo86GlLH2Jt9mglNjajZJYaXiahE7cQYHSjRXry4MMYv07/LONYNG4gYj61rF4BlGTQkKfq7r784Od7RyHDewy6wrCuju+B7x0/SifnDnRDOKKWBTEqgvu8ML4jflLbyFRXQGOTNmT5ArjwhCWpTnO+InSfo0dvUcv//4Mwv18Ieh14UUWqNe+WqN701lQAKwnsLo9WeZEGkA2qUVVy6U0I1NdnnB/f/NNsUhTAhkEdrS3PqmMIl3FiDwBi06ONa6ZiDkdDcNJaY7H+z2BQh62OhR8ByCbNx8m+K6rSYQizJWURW+P2YRApEyj26ZdqwRJKyXLFg57MFLs/DEjbB7tXfgsGhVttbVzzg1Ok7jRqVelT+D1G4QPTLxBJgyyg4BhIVKRv//kSL7BsNT2Y4GJnEztWX2FHxSrWYwm5oJGkDGlYP8brMS4ji9rUqp9IRuwQknMoc+zqdqI8iaUyEZdYI19PQAzjiDy+jEyVXM4A3Xe1eaK+qwGRtWG1MmFNZ1zYndSU467G/kImtLDm5RXxQaHLjG/EwqiIFhGWFrjDyM9y17GUpq/Qk5EMAF5r9T5zXSmM4ou8wpfqPh7UQ6XOibNz/9mzYtoINwhjEX23PHy08GDCDldk/1A==
    grafana-admin-user: AgBFI7Z9ceOE8TSPywfja6qH5CUh/OT/UYWBhC4ipM7T+SaXfFCN77QLLntgbqrBYA2oWkJtm8JOgnjsnxvgAd9m/Ez2jjJyHKhBczpfG4wM2U+Xh6pvfJIWbKrueFBAUU+VhC9FA7tNIsoUzuR9lJxkJxmRP3i8qNN+nsPwlhZxQZ/B5TkN6IdZl74PgCv85u1jegxPNtHO72UA5cMNJY6CXKq61M9ftiBqxrcgNZoA67oBuehEEwrl5BN4ptgLNJCXEbbCk5+MxwK0e30MxJ0cVOii0OMM2p6gtOQcwML45JhbJksCOUolDo+9PVSTpPyLEZufA8jwxX9SLcbrbMaxPDkgxkPDlvXtzYIpSeFHPxMMNG0Ftavgie3dy8ogi2gJm2h7pWmct3y52YCIZK4KjMLXK0MM7qv5U3RPHsfQpzqU9cgwZ5x+8FpGJ4RpJts5hZwNVXLpmIqqLhN0N4MBH6MTzbhPngyKUgEov3kw7124klABlM9sD9Vv58bP771Kob3Xm8L52cj5ECp4oUyXVoQiGjrKVB6lTWgK1TFRFMElpf9qSTMWJFOzZlXsRdAch/hXP2bWnJZgPvblDAtHgt+MheVfKLgQL78bAd6k5iOzBmL5gZQCYvsWFVp64B/fodkdb5nwpVv1W7DFaFCOvuc652cCkgUK72jysJEKddY3q2CEdJjgaL3Pcnk+Vc4ljqpiww==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: grafana-secrets
    type: Opaque
