---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
spec:
  encryptedData:
    grafana-admin-password: AgAOvIW6yb1JFW5yJS/Ac8fnMNMbQNn3de+FfB6blQik8mIOLVRLYaEjjPWLe1pT5XghOuHrp6c6AQzp5Tv1v5TTyX0POhZohuS8SRBOkw2XTyDY0MxTMElDS+QTVKql3ghaAA2Wnmhfec114agWXpGqCt2IH66j9iPEZLYQ/61EX8UkNz/xcI7PamSz9SHXVQ+IVAjrQg9FNZLQz4luGcbNO0LNwRuBBJLPr2eMhJilik9APAIoX8/rg0PKT6F49us4Oc9EVzRGWki/EYWScqyWT8Z0jRbX9b6G4MLFRINYRhFPP8qEiemKolANRsx3w5iV5gNjWTlvQM7koD/Fg4u3NkVbU96R9ClnxrENOt2MSw0KPHcR449lf/Gyy+t9AdX5CgPXAPky3ouTMqsjfHMIkFhmeRQYe2S/enVc3DMg9aOELiSR4091Auh1RPUXDJ5BJhRjfvndYqUa/eEsgJGJrD/pNVPjK9F0LDvJuh3oops4OZ54vxgf2WsF7/kAVF+j3jlUVrjULunaYmTxbeBNRG6YltDX5iil6CRg1B/Mi6B6veNz+ygLBAOfuA2susRXzgbAJRRvHBOMsgu7EQw27ak4b5EBSyrh0Orr/RjxBZKl/IfziRay1MUM2pPnBG1L0iSrRYc8Qlzu4xPsphfbMns3YQTh31J0QEGrGr+XojPVbkLyRrI84h2REy6uUFCxroUZe0cJQM+JT39yIDJfCoHGLeGmyaYLmjDD7DxdFw==
    grafana-admin-user: AgBOQOzksaKq9U2SPTZPtI8Hcr4PA07oNirc7QPR8qExWmQDNBdw1nUDdK/hw8gnlBMyiZzOcEsWwueDIUUJHJPujZ0auw39w8HShdwUltOaT11qwzgxTfnRAeNBU1PpAZrDELq4A5vYMAPH67tpHb7tWVQ+30c4BFe80ur78lY4GNYImDjkiPakzxIRwYEPdGUltIcMb8ByZxputQzSoI58LRWQFxlV6RJ1ozx4bWsNaHF+b3lDHG//BVNG4C6t1XOyFOh7ZkXW+G8B2w3LXx5C+Gj3cU4kQtR3idGfUf4u+r00HEfCpyD9phqB0Qnm1C+0ITNWhO8HBligRVJ83Bbmv5UVxJn86Q/VCTE3jGjO5EdCjzv8JHpFkdAQownLi1/eUBnXwUy3/Bp/0yNekt1JjdBNeUf2bbbGwDh5IJYzR806mLT7XXL/qcmpSA6895bCw0UQE5M+cgrrLjk9zw4YSXvnWxvOqclH+usDPVdN8HTcsoO26qRp52/9wmnwb/UjyWE5G/xQ/61BWx6dfA+fmcN+12/3H99ENfQZqWwUzF2KI7nvw5iYsICSX8oA0QXxLjPQuaPCKxJOME7fMr1uGRKREX7wbegfLJq9siZ+cAfhbSMopjcdYjVKfDmx5k2HTwqKRe9ISfApxXF+Q9CH+IdwX0+Nl4OFNuPeKm2WHDCMrOUKtOKhLQJXiZs2ay+o+1boDQ==
    # Grafana user in grafana-zabbix datasource
    # grafana-zabbix-password: <>
    # grafana-zabbix-user: <>
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
    type: Opaque
