apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Tiagura/k8s-gitops.git
        revision: HEAD
        directories:
          - path: infrastructure/controllers/*
          - path: infrastructure/networking/*
          - path: infrastructure/storage/*
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      labels:
        app.kubernetes.io/part-of: infrastructure
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/Tiagura/k8s-gitops.git
        targetRevision: HEAD
        path: '{{path}}'
        plugin:
          name: kustomize-build-with-helm
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      info:
        - name: Description
          value: 'Infrastructure component: {{path.basename}}'