apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Tiagura/k8s-gitops.git
        revision: HEAD
        directories:
          - path: apps/*/*
  template:
    metadata:
      name: 'apps-{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
        argocd.argoproj.io/compare-options: ServerSideDiff=true
      labels:
        app.kubernetes.io/part-of: infrastructure
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/Tiagura/k8s-gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
      info:
        - name: Description
          value: 'App component: {{path.basename}}'