apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  labels:
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/component: argocd
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/Tiagura/k8s-gitops.git
    targetRevision: main
    path: infrastructure/controllers/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /spec/rules/0/backendRefs/0/weight
        - /spec/rules/0/backendRefs/0/kind
        - /spec/rules/0/backendRefs/0/group
  info:
    - name: Description
      value: 'ArgoCD for GitOps continuous delivery'