apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/Tiagura/k8s-gitops.git
    targetRevision: main
    path: infrastructure/controllers/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 5m
  info:
    - name: Description
      value: 'Cert-Manager for managing TLS certificates'