# Essential: Cilium App of ArgoCD
# Wave 0, all components relying on networking ready
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  labels:
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/component: networking
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/Tiagura/k8s-gitops.git
    targetRevision: main
    path: infrastructure/networking/cilium
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 5m
  info:
    - name: Description
      value: 'Cilium CNI for cluster networking'