apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-wide-resources
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-wide-resources
  source:
    repoURL: https://github.com/Tiagura/k8s-gitops.git
    targetRevision: main
    path: resources/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 5m
  info:
    - name: Description
      value: 'Cluster Wide Resources'