# Essential: Sealed Secrets App of ArgoCD
# Wave 0, to unseal sealed secrets for other components
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  labels:
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/Tiagura/k8s-gitops.git
    targetRevision: main
    path: infrastructure/controllers/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  info:
    - name: Description
      value: 'Sealed Secrets for managing encrypted secrets in the cluster'