# stremio-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stremio-pvc
  namespace: stremio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn