apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ingress-from-kubectl-cnpg-plugin
spec:
  description: >
    Allow ingress traffic from kubectl cnpg plugin pods to all database clusters.
  endpointSelector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
  ingress:
    - fromEntities:
        - remote-node
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP