{
 "title": "Cilium Metrics",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "tags": [
  "cilium",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(cilium_endpoint,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Errors & Warnings",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_errors_warnings_total{instance=~\"$instance\"}[1m])) by (instance, level) * 60",
     "legendFormat": "{{level}} {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage per instance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min(irate(cilium_process_cpu_seconds_total{instance=~\"$instance\"}[1m])) by (instance) * 100",
     "legendFormat": "min {{instance}}"
    },
    {
     "expr": "avg(irate(cilium_process_cpu_seconds_total{instance=~\"$instance\"}[1m])) by (instance) * 100",
     "legendFormat": "avg {{instance}}"
    },
    {
     "expr": "max(irate(cilium_process_cpu_seconds_total{instance=~\"$instance\"}[1m])) by (instance) * 100",
     "legendFormat": "max {{instance}}"
    }
   ]
  },
  {
   "title": "Generic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Memory Bytes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "min(cilium_process_virtual_memory_bytes{instance=~\"$instance\"})",
       "legendFormat": "Min Virtual Memory"
      },
      {
       "expr": "avg(cilium_process_virtual_memory_bytes{instance=~\"$instance\"})",
       "legendFormat": "Average Virtual Memory"
      },
      {
       "expr": "max(cilium_process_virtual_memory_bytes{instance=~\"$instance\"})",
       "legendFormat": "Max Virtual Memory"
      }
     ]
    },
    {
     "title": "Resident memory status",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(cilium_process_resident_memory_bytes{instance=~\"$instance\"})",
       "legendFormat": "AVG_resident_memory_bytes"
      },
      {
       "expr": "max(cilium_process_resident_memory_bytes{instance=~\"$instance\"})",
       "legendFormat": "MAX_resident_memory_bytes_max"
      },
      {
       "expr": "min(cilium_process_resident_memory_bytes{instance=~\"$instance\"})",
       "legendFormat": "MIN_resident_memory_bytes_min"
      }
     ]
    },
    {
     "title": "Open file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cilium_process_open_fds{instance=~\"$instance\"})",
       "legendFormat": "all nodes"
      },
      {
       "expr": "min(cilium_process_open_fds{instance=~\"$instance\"})",
       "legendFormat": "min/instance"
      },
      {
       "expr": "avg(cilium_process_open_fds{instance=~\"$instance\"})",
       "legendFormat": "avg/instance"
      },
      {
       "expr": "max(cilium_process_open_fds{instance=~\"$instance\"})",
       "legendFormat": "max/instance"
      }
     ]
    },
    {
     "title": "System-wide BPF memory usage",
     "type": "timeseries",
     "description": "BPF memory usage in the entire system including components not managed by Cilium.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(cilium_bpf_maps_virtual_memory_max_bytes{instance=~\"$instance\"} + cilium_bpf_progs_virtual_memory_max_bytes{instance=~\"$instance\"})",
       "legendFormat": "AVG_bpf_memory_bytes_avg"
      },
      {
       "expr": "max(cilium_bpf_maps_virtual_memory_max_bytes{instance=~\"$instance\"} + cilium_bpf_progs_virtual_memory_max_bytes{instance=~\"$instance\"})",
       "legendFormat": "MAX_bpf_memory_bytes_max"
      },
      {
       "expr": "min(cilium_bpf_maps_virtual_memory_max_bytes{instance=~\"$instance\"} + cilium_bpf_progs_virtual_memory_max_bytes{instance=~\"$instance\"})",
       "legendFormat": "MIN_bpf_memory_bytes_min"
      }
     ]
    },
    {
     "title": "BPF map pressure",
     "type": "timeseries",
     "description": "Fill percentage of BPF maps, tagged by map name",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "cilium_bpf_map_pressure{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "API call latency (average instance)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_agent_api_process_time_seconds_sum{instance=~\"$instance\"}[1m])/rate(cilium_agent_api_process_time_seconds_count{instance=~\"$instance\"}[1m])) by (instance, method, path)",
       "legendFormat": "{{method}} {{path}} {{instance}}"
      }
     ]
    },
    {
     "title": "API call latency (max instance)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(rate(cilium_agent_api_process_time_seconds_sum{instance=~\"$instance\"}[1m])/rate(cilium_agent_api_process_time_seconds_count{instance=~\"$instance\"}[1m])) by (instance, method, path)",
       "legendFormat": "{{method}} {{path}} {{instance}}"
      }
     ]
    },
    {
     "title": "# API calls (average instance)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{instance=~\"$instance\"}[1m])) by (instance, method, path)",
       "legendFormat": "{{method}} {{path}} {{instance}}"
      }
     ]
    },
    {
     "title": "# API calls (max instance)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max(rate(cilium_agent_api_process_time_seconds_count{instance=~\"$instance\"}[1m])) by (instance, method, path)",
       "legendFormat": "{{method}} {{path}} {{instance}}"
      }
     ]
    },
    {
     "title": "API return codes (average instance)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{instance=~\"$instance\"}[1m])) by (instance, method, path, return_code)",
       "legendFormat": "{{return_code}} ({{method}} {{path}} {{instance}} )"
      }
     ]
    },
    {
     "title": "API return codes (sum all nodes)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_agent_api_process_time_seconds_count{instance=~\"$instance\"}[1m])) by (instance, method, path, return_code)",
       "legendFormat": "{{return_code}} ({{method}} {{path}} {{instance}} )"
      }
     ]
    }
   ]
  },
  { "title": "Cilium", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "title": "BPF", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "map ops (average instance)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, avg(rate(cilium_bpf_map_ops_total{instance=~\"$instance\"}[5m])) by (instance, map_name, operation))",
     "legendFormat": "{{map_name}} {{operation}} {{instance}}"
    }
   ]
  },
  {
   "title": "map ops (max instance)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, max(rate(cilium_bpf_map_ops_total{instance=~\"$instance\"}[5m])) by (instance, map_name, operation))",
     "legendFormat": "{{map_name}} {{operation}} {{instance}}"
    }
   ]
  },
  {
   "title": "map ops (sum failures)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_bpf_map_ops_total{outcome=\"fail\",  instance=~\"$instance\"}[5m])) by (instance, map_name, operation)",
     "legendFormat": "{{map_name}} {{operation}} {{instance}}"
    }
   ]
  },
  { "title": "kvstore", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "latency (average instance)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, avg(rate(cilium_kvstore_operations_duration_seconds_sum{ instance=~\"$instance\"}[1m])) by (instance, action, scope) / avg(rate(cilium_kvstore_operations_duration_seconds_count{ instance=~\"$instance\"}[1m])) by (instance, action, scope))",
     "legendFormat": "{{action}} {{scope}} {{instance}}"
    }
   ]
  },
  {
   "title": "latency (max instance)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(rate(cilium_kvstore_operations_duration_seconds_sum{ instance=~\"$instance\"}[1m])) by (instance, action, scope) / avg(rate(cilium_kvstore_operations_duration_seconds_count{ instance=~\"$instance\"}[1m])) by (instance, action, scope))",
     "legendFormat": "{{action}} {{scope}} {{instance}}"
    }
   ]
  },
  {
   "title": "Events received (average  instance)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kvstore_events_queue_seconds_count{ instance=~\"$instance\"}[1m])) by ( instance, scope, action)",
     "legendFormat": "{{action}} {{scope}} {{ instance}}"
    }
   ]
  },
  { "title": "Cilium network information", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Forwarded Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_forward_count_total{instance=~\"$instance\"}[1m])) by ( instance, direction)",
     "legendFormat": "{{direction}} {{ instance}}"
    }
   ]
  },
  {
   "title": "Forwarded Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_forward_bytes_total{instance=~\"$instance\"}[1m])) by ( instance, direction) * 8",
     "legendFormat": "{{direction}} {{ instance}}"
    }
   ]
  },
  {
   "title": "IPv4 Conntrack TCP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{ status=\"alive\", family=\"ipv4\", protocol=\"TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{ status=\"alive\", family=\"ipv4\", protocol=\"TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{ status=\"alive\", family=\"ipv4\", protocol=\"TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{ status=\"deleted\", family=\"ipv4\", protocol=\"TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{ status=\"deleted\", family=\"ipv4\", protocol=\"TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "IPv6 Conntrack TCP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{ status=\"alive\", family=\"ipv6\", protocol=\"TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{ status=\"alive\", family=\"ipv6\", protocol=\"TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{ status=\"alive\", family=\"ipv6\", protocol=\"TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{ status=\"deleted\", family=\"ipv6\", protocol=\"TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{ status=\"deleted\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "IPv4 Conntrack Non-TCP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{ status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{ status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{ status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{ status=\"deleted\", family=\"ipv4\", protocol=\"non-TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{ status=\"deleted\", family=\"ipv4\", protocol=\"non-TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "IPv6 Conntrack Non-TCP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{ status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{ status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{ status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{ status=\"deleted\", family=\"ipv6\", protocol=\"non-TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{ status=\"deleted\", family=\"ipv6\", protocol=\"non-TCP\",  instance=~\"$instance\"}) by (family,status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "Allocated Addresses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_ip_addresses{instance=~\"$instance\"}) by ( instance, family)\n",
     "legendFormat": "{{family}} {{ instance}}"
    }
   ]
  },
  {
   "title": "Datapath Conntrack Dump Resets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_datapath_conntrack_dump_resets_total{instance=~\"$instance\"}) by ( instance, area, family, name)",
     "legendFormat": "{{name}} {{area}} {{family}} {{ instance}}"
    }
   ]
  },
  {
   "title": "Service Updates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_nodes_all_events_received_total{instance=~\"$instance\"}[1m])) by ( instance, action)",
     "legendFormat": "{{action}} {{ instance}}"
    }
   ]
  },
  {
   "title": "Connectivity Health",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_unreachable_nodes{instance=~\"$instance\"}) by ( instance)",
     "legendFormat": "unreachable nodes {{ instance}}"
    },
    {
     "expr": "sum(cilium_unreachable_health_endpoints{instance=~\"$instance\"}) by ( instance)",
     "legendFormat": "unreachable health endpoints {{ instance}}"
    }
   ]
  },
  {
   "title": "Dropped Egress Packets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{direction=\"EGRESS\", instance=~\"$instance\"}[1m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Node Events",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_nodes_all_events_received_total{instance=~\"$instance\"}[1m])) by ( instance, event_type, source) * 60",
     "legendFormat": "{{eventType}} {{source}} {{ instance}}"
    }
   ]
  },
  {
   "title": "Dropped Egress Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_bytes_total{direction=\"EGRESS\", instance=~\"$instance\"}[1m])) by (reason) * 8",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(cilium_nodes_all_num{instance=~\"$instance\"}) by ( instance)",
     "legendFormat": "Average Nodes {{ instance}}"
    },
    {
     "expr": "min(cilium_nodes_all_num{instance=~\"$instance\"}) by ( instance)",
     "legendFormat": "Min Nodes {{ instance}}"
    },
    {
     "expr": "max(cilium_nodes_all_num{instance=~\"$instance\"}) by ( instance)",
     "legendFormat": "Max Nodes {{ instance}}"
    }
   ]
  },
  { "title": "Policy", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "L7 forwarded request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_policy_l7_total{instance=~\"$instance\", rule=\"denied\"}[1m]))",
     "legendFormat": "denied"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_total{instance=~\"$instance\", rule=\"forwarded\"}[1m]))",
     "legendFormat": "forwarded"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_total{instance=~\"$instance\", rule=\"received\"}[1m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Cilium drops Ingress",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{direction=\"INGRESS\", instance=~\"$instance\"}[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Proxy response time (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_proxy_upstream_reply_seconds_sum{instance=~\"$instance\"}[1m])) by ( instance, scope) / sum(rate(cilium_proxy_upstream_reply_seconds_count{instance=~\"$instance\"}[1m])) by ( instance, scope)",
     "legendFormat": "{{scope}}"
    },
    {
     "expr": "avg(cilium_policy_l7_total{instance=~\"$instance\", rule=\"parse_errors\"}) by (instance)",
     "legendFormat": "parse errors {{instance}}"
    }
   ]
  },
  {
   "title": "Dropped Ingress Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_bytes_total{direction=\"INGRESS\", instance=~\"$instance\"}[1m])) by (reason) * 8",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Policy Trigger Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min(rate(cilium_policy_incremental_update_duration_sum{instance=~\"$instance\"}[1m])) by (instance, scope) / sum(rate(cilium_policy_incremental_update_duration_count{instance=~\"$instance\"}[1m])) by (instance, scope)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(rate(cilium_policy_incremental_update_duration_sum{instance=~\"$instance\"}[1m])) by (instance, scope) / sum(rate(cilium_policy_incremental_update_duration_count{instance=~\"$instance\"}[1m])) by (instance, scope)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(rate(cilium_policy_incremental_update_duration_sum{instance=~\"$instance\"}[1m])) by (instance, scope) / sum(rate(cilium_policy_incremental_update_duration_count{instance=~\"$instance\"}[1m])) by (instance, scope)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Proxy response time (Max)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(cilium_proxy_upstream_reply_seconds_sum{instance=~\"$instance\"}[1m])) by (instance, scope) / sum(rate(cilium_proxy_upstream_reply_seconds_count{instance=~\"$instance\"}[1m])) by (instance, scope)",
     "legendFormat": "Max {{scope}}"
    },
    {
     "expr": "max(rate(cilium_policy_l7_total{instance=~\"$instance\", rule=\"parse_errors\"}[1m])) by (instance)",
     "legendFormat": "parse errors {{instance}}"
    }
   ]
  },
  {
   "title": "Endpoints policy enforcement status",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(cilium_policy_endpoint_enforcement_status{instance=~\"$instance\"}) by (enforcement)",
     "legendFormat": "{{enforcement}}"
    }
   ]
  },
  {
   "title": "Policy Trigger Runs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "min(rate(envoy_cilium_policy_updates_total{instance=~\"$instance\"}[1m])) by (instance) * 60",
     "legendFormat": "min trigger {{instance}}"
    },
    {
     "expr": "avg(rate(envoy_cilium_policy_updates_total{instance=~\"$instance\"}[1m])) by (instance) * 60",
     "legendFormat": "average trigger"
    },
    {
     "expr": "max(rate(envoy_cilium_policy_updates_total{ pod=~\"$pod\"}[1m])) by (pod) * 60",
     "legendFormat": "max trigger {{instance}}"
    },
    {
     "expr": "max(rate(envoy_cilium_policy_updates_rejected{instance=~\"$instance\"}[1m])) by (instance) * 60",
     "legendFormat": "folds {{instance}}"
    }
   ]
  },
  {
   "title": "Policies Per Node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_policy{instance=~\"$instance\"}) by(instance)",
     "legendFormat": "min {{instance}}"
    },
    {
     "expr": "avg(cilium_policy{instance=~\"$instance\"}) by(instance)",
     "legendFormat": "avg {{instance}}"
    },
    {
     "expr": "max(cilium_policy{instance=~\"$instance\"}) by(instance)",
     "legendFormat": "max {{instance}}"
    },
    {
     "expr": "sum(cilium_policy_change_total{instance=~\"$instance\", outcome=\"failure\"}) by (instance)",
     "legendFormat": "policy change errors {{instance}}"
    }
   ]
  },
  {
   "title": "Policy Revision",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_policy_max_revision{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "min {{instance}}"
    },
    {
     "expr": "avg(cilium_policy_max_revision{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "avg {{instance}}"
    },
    {
     "expr": "max(cilium_policy_max_revision{ pod=~\"$pod\"}) by (pod)",
     "legendFormat": "max {{instance}}"
    }
   ]
  },
  { "title": "Endpoints", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Endpoint regeneration time (90th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90, rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{ scope!=\"total\",  instance=~\"$instance\"}[5m]))) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Endpoint regeneration time (99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99, rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{scope!=\"total\", instance=~\"$instance\"}[5m]))) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Endpoint regenerations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_endpoint_regenerations_total{instance=~\"$instance\"}[1h])) by(outcome)",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Cilium endpoint state",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_endpoint_state{instance=~\"$instance\"}) by (endpoint_state)",
     "legendFormat": "{{endpoint_state}}"
    }
   ]
  },
  { "title": "Controllers", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Controllers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_controllers_runs_total{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "Runs"
    },
    {
     "expr": "sum(cilium_controllers_failing{ pod=~\"$pod\"}) by(pod)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Controller Durations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_controllers_runs_duration_seconds_sum{instance=~\"$instance\"}[1m])) by (instance, status) / sum(rate(cilium_controllers_runs_duration_seconds_count{instance=~\"$instance\"}[1m])) by (instance, status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Kubernetes integration", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "apiserver latency (average instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_k8s_client_api_latency_time_seconds_sum{instance=~\"$instance\"}[1m])/rate(cilium_k8s_client_api_latency_time_seconds_count{instance=~\"$instance\"}[1m])) by (instance, method, path)",
     "legendFormat": "{{method}} {{path}} {{instance}}"
    }
   ]
  },
  {
   "title": "apiserver latency (max instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(cilium_k8s_client_api_latency_time_seconds_sum{instance=~\"$instance\"}[1m])/rate(cilium_k8s_client_api_latency_time_seconds_count{instance=~\"$instance\"}[1m])) by (instance, method, path)",
     "legendFormat": "{{method}} {{path}} {{instance}}"
    }
   ]
  },
  {
   "title": "apiserver #calls (sum all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_k8s_client_api_latency_time_seconds_count{instance=~\"$instance\"}[1m])) by (instance, method, path)",
     "legendFormat": "{{method}} {{path}} {{instance}}"
    }
   ]
  },
  {
   "title": "apiserver calls (sum all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_k8s_client_api_calls_total{instance=~\"$instance\"}[1m])) by (instance, method, return_code)",
     "legendFormat": "{{method}} {{return_code}} {{instance}}"
    }
   ]
  },
  {
   "title": "Valid, Unnecessary K8s Events Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{equal=\"true\", valid=\"true\", instance=~\"$instance\"}[5m])) by (instance, scope, action)",
     "legendFormat": "{{action}} {{scope}} {{instance}}"
    }
   ]
  },
  {
   "title": "Invalid, Unnecessary K8s Events Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{ equal=\"true\", valid=\"false\", instance=~\"$instance\"}[5m])) by (instance, scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Valid, Necessary K8s Events Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{ equal=\"false\", valid=\"true\",  instance=~\"$instance\"}[5m])) by (instance, scope, action, valid)",
     "legendFormat": "{{action}} {{scope}} {{instance}}"
    }
   ]
  },
  {
   "title": "Invalid, Necessary K8s Events Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{ equal=\"true\", valid=\"true\",  instance=~\"$instance\"}[5m])) by (instance, scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "CiliumNetworkPolicy Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{ scope=\"CiliumNetworkPolicy\",  instance=~\"$instance\"}[1m])) by (instance, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "NetworkPolicy Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{ scope=\"NetworkPolicy\",  instance=~\"$instance\"}[1m])) by (instance, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Pod Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{ scope=\"Pod\",  instance=~\"$instance\"}[1m])) by (instance, action) * 60",
     "legendFormat": "{{action}} avg {{instance}}"
    }
   ]
  },
  {
   "title": "Node Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{ scope=\"Node\",  instance=~\"$instance\"}[1m])) by (instance, action) * 60",
     "legendFormat": "{{action}} avg {{instance}}"
    }
   ]
  },
  {
   "title": "Service Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{ scope=\"Service\",  instance=~\"$instance\"}[1m])) by (instance, action) * 60",
     "legendFormat": "{{action}} {{instance}}"
    }
   ]
  },
  {
   "title": "Endpoints Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{ scope=\"Endpoint\",  instance=~\"$instance\"}[1m])) by (instance, action) * 60",
     "legendFormat": "{{action}} {{instance}}"
    }
   ]
  },
  {
   "title": "Namespace Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{ scope=\"Namespace\",  instance=~\"$instance\"}[1m])) by (instance, action) * 60",
     "legendFormat": "{{action}} {{instance}}"
    }
   ]
  }
 ]
}