{
 "title": "Proxmox OpenTelemetry Dashboard",
 "description": "Monitoring Proxmox with OpenTelemetry Grafana",
 "tags": [
  "Proxmox",
  "OpenTelemetry"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "dsProxmox", "label": "Datasource", "query": "prometheus" },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(proxmox_node_uptime_seconds,node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "Server CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxmox_node_cpustat_cpu_percent{node=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logical Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxmox_node_cpustat_cpus_ratio{node=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxmox_node_memory_memtotal_bytes{node=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxmox_node_memory_swaptotal_bytes{node=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Pools",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxmox_storage_used_bytes{node=\"$server\"} / proxmox_storage_total_bytes{node=\"$server\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxmox_node_cpustat_avg1_ratio{node=\"$server\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "proxmox_node_cpustat_avg5_ratio{node=\"$server\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "proxmox_node_cpustat_avg15_ratio{node=\"$server\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Memory in Use",
   "type": "stat",
   "description": "Memory in use by Host OS, VM's and Containers",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxmox_node_memory_memused_bytes{node=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Wait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxmox_node_uptime_seconds{node=\"$server\"} / proxmox_node_cpustat_iowait_seconds_total{node=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster summary of Resources $server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "VM List",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "proxmox_vm_uptime_seconds{node=~\"$server\", type=\"qemu\"}"
    },
    {
     "expr": "proxmox_vm_cpus_ratio{node=~\"$server\", type=\"qemu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "proxmox_vm_maxdisk_bytes{node=~\"$server\", type=\"qemu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "proxmox_vm_maxmem_bytes{node=~\"$server\", type=\"qemu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "proxmox_vm_mem_bytes{node=~\"$server\", type=\"qemu\"} / proxmox_vm_maxmem_bytes{node=~\"$server\", type=\"qemu\"} * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "proxmox_vm_cpu_percent{node=~\"$server\", type=\"qemu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "proxmox_vm_uptime_seconds{node=~\"$server\", type=\"qemu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LXC List",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "proxmox_vm_uptime_seconds{node=~\"$server\", type=\"lxc\"}"
    },
    {
     "expr": "proxmox_vm_cpus_ratio{node=~\"$server\", type=\"lxc\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "proxmox_vm_maxdisk_bytes{node=~\"$server\", type=\"lxc\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "proxmox_vm_maxmem_bytes{node=~\"$server\", type=\"lxc\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "proxmox_vm_mem_bytes{node=~\"$server\", type=\"lxc\"} / proxmox_vm_maxmem_bytes{node=~\"$server\", type=\"lxc\"} * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "proxmox_vm_cpu_percent{node=~\"$server\", type=\"lxc\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "proxmox_vm_uptime_seconds{node=~\"$server\", type=\"lxc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory and CPU usage $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Host CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "proxmox_node_cpustat_cpu_percent{node=~\"$server\"}",
     "legendFormat": "cpu {{node}}"
    },
    {
     "expr": "(proxmox_node_uptime_seconds{node=\"$server\"} / proxmox_node_cpustat_iowait_seconds_total{node=\"$server\"}) * 100",
     "legendFormat": "wait {{node}}"
    },
    {
     "expr": "proxmox_node_cpustat_avg1_ratio{node=~\"$server\"}",
     "legendFormat": "avg1 {{node}}"
    },
    {
     "expr": "proxmox_node_cpustat_avg5_ratio{node=~\"$server\"}",
     "legendFormat": "avg5 {{node}}"
    },
    {
     "expr": "proxmox_node_cpustat_avg15_ratio{node=~\"$server\"}",
     "legendFormat": "avg15 {{node}}"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "proxmox_node_memory_memtotal_bytes{node=~\"$server\"}",
     "legendFormat": "memtotal {{node}}"
    },
    {
     "expr": "proxmox_node_memory_memused_bytes{node=~\"$server\"}",
     "legendFormat": "memused {{node}}"
    }
   ]
  },
  {
   "title": "VM CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "proxmox_vm_cpu_percent{node=~\"$server\", type=\"qemu\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "VM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "proxmox_vm_mem_bytes{node=~\"$server\", type=\"qemu\"} / proxmox_vm_maxmem_bytes{node=~\"$server\", type=\"qemu\"} * 100",
     "legendFormat": "{{name}} {{node}}"
    }
   ]
  },
  {
   "title": "LXC CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "proxmox_vm_cpu_percent{node=~\"$server\", type=\"lxc\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "LXC memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "proxmox_vm_mem_bytes{node=~\"$server\", type=\"lxc\"} / proxmox_vm_maxmem_bytes{node=~\"$server\", type=\"lxc\"} * 100",
     "legendFormat": "{{name}} {{node}}"
    }
   ]
  },
  {
   "title": "VM I/O Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "proxmox_vm_diskread_bytes_total{node=~\"$server\", type=\"qemu\"} / proxmox_vm_uptime_seconds{node=~\"$server\", type=\"qemu\"} * 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VMs I/O Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "proxmox_vm_diskwrite_bytes_total{node=~\"$server\", type=\"qemu\"} / proxmox_vm_uptime_seconds{node=~\"$server\", type=\"qemu\"} * 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LXC I/O Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "proxmox_vm_diskread_bytes_total{node=~\"$server\", type=\"lxc\"} / proxmox_vm_uptime_seconds{node=~\"$server\", type=\"lxc\"} * 10",
     "legendFormat": "{{name }} {{node}}"
    }
   ]
  },
  {
   "title": "LXC I/O Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "proxmox_vm_diskwrite_bytes_total{node=~\"$server\", type=\"lxc\"} / proxmox_vm_uptime_seconds{node=~\"$server\", type=\"lxc\"} * 10",
     "legendFormat": "{{name}} {{node}}"
    }
   ]
  },
  {
   "title": "VM traffic In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "proxmox_vm_netin_bytes_total{node=~\"$server\", type=\"qemu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM traffic out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "proxmox_vm_netout_bytes_total{node=~\"$server\", type=\"qemu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LXC traffic In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "proxmox_vm_netin_bytes_total{node=~\"$server\", type=\"lxc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LXC traffic out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "proxmox_vm_netout_bytes_total{node=~\"$server\", type=\"lxc\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}