{
 "title": "Tailscale - VPN",
 "description": "Tailscale - Point to point VPN. Shows traffic and some other metrics. dashboard retrieved from random guy on the internet.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "All stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Subnet Router",
   "type": "stat",
   "description": "Advertised and approved subnet routes",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tailscaled_advertised_routes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Advertised Routes"
    },
    {
     "expr": "tailscaled_approved_routes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Approved Routes"
    }
   ]
  },
  {
   "title": "Health Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tailscaled_health_messages{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "### Colors\n\nPurple = inbound traffic  \nBlue = outbound traffic"
   }
  },
  {
   "title": "All Traffic",
   "type": "timeseries",
   "description": "Inbound/outbound bytes/sec per interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  rate(tailscaled_inbound_packets_total{job=\"$job\", instance=~\"$instance\", path=~\"direct_.*\"}[$__rate_interval])\r\n)*8",
     "legendFormat": "{{instance}} RX {{path}}"
    },
    {
     "expr": "sum by (instance) (\r\n  rate(tailscaled_outbound_packets_total{job=\"$job\", instance=~\"$instance\", path=~\"direct_.*\"}[$__rate_interval])\r\n)*8",
     "legendFormat": "{{instance}} TX {{path}}"
    }
   ]
  },
  {
   "title": "Errors (TX/RX)",
   "type": "timeseries",
   "description": "Dropped Packets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(tailscaled_inbound_dropped_packets_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} RX {{reason}}"
    },
    {
     "expr": "rate(tailscaled_outbound_dropped_packets_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} TX {{reason}}"
    }
   ]
  },
  { "title": "Direct Traffic (P2P)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Inbound",
   "type": "timeseries",
   "description": "Traffic from direct peer-to-peer connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  rate(tailscaled_inbound_packets_total{job=\"$job\", instance=~\"$instance\", path=~\"direct_.*\"}[$__rate_interval])\r\n)",
     "legendFormat": "{{instance}} RX {{path}}"
    }
   ]
  },
  {
   "title": "Outbound",
   "type": "timeseries",
   "description": "Traffic to direct peer-to-peer connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  rate(tailscaled_outbound_packets_total{job=\"$job\", instance=~\"$instance\", path=~\"direct_.*\"}[$__rate_interval])\r\n)",
     "legendFormat": "{{instance}} TX {{path}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "options": {
    "content": "### P2P\n\nTailscale is an encrypted point-to-point VPN service that streamlines connecting devices and services securely across different networks with WireGuard.\n\nTailscale docs: https://tailscale.com/kb/1151/what-is-tailscale"
   }
  },
  { "title": "Relayed Traffic (DERP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Inbound",
   "type": "timeseries",
   "description": "Traffic from relayed connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(tailscaled_inbound_packets_total{job=\"$job\", instance=~\"$instance\", path=\"derp\"}[$__rate_interval])",
     "legendFormat": "{{instance}} RX {{path}}"
    }
   ]
  },
  {
   "title": "Outbound",
   "type": "timeseries",
   "description": "Traffic to relayed connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(tailscaled_outbound_packets_total{job=\"$job\", instance=~\"$instance\", path=\"derp\"}[$__rate_interval])",
     "legendFormat": "{{instance}} TX {{path}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "### DERP\n\nDERP (Designated Encrypted Relay for Packets) servers manage device connections and NAT traversal. They serve two primary purposes: negotiating direct connections between tailnet devices and serving as a relay server when a direct connection isn’t possible.\n\nTailscale docs: https://tailscale.com/kb/1232/derp-servers"
   }
  }
 ]
}