---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: memos-secrets
spec:
  encryptedData:
    db_password: AgBTWYbihrcSMHhP7X2tFG98R/sRjaf+teHoG5GKzza2GjNXAPpZ8y1lb0ASyYrQzQqemjyXREGCQYYa4Ex+ALkTqQV1fUQEaVrsJay37rDn/jvutFd3zDm1OhvUNXyt58y4n6T/j10ByUfsY/+KTJVGiyxGZI5QGO0fCJYVy9mR3B0fG/p4mVYt+/4V43Vj8Qo2fXBpRwlPATuudrpG0mu2z4QBJoC8KiPT2bqMFLd1t9Rs/ZUEJNQS5WLgzTDyc9hxaSQ4aiEpdEet0GPgwHmbOw/IMtQRKGIv7gHwSpBgCPUvTFRnS7Nr1zEzNiUBjcuplArTFwOu7CcFglFv/rfvvzODYJArGdkq8G/Nb7EIUriDdHiZbdQ5jwdQEwogL9rqMJ3m/LIQRiY+W5IoHP+DLSLohIW9hYBLPdZ4LdYg+2LteTqUpQyVzYb7heSjS44P/lkuwtojllZOI/4VAO02R5z7H4OFgwloCYcShcPyhozC24FPe/XoF5qAbzO51IZU15N5Hx4eTj9lyU65R7ebwCJPwpTSVzSE8IlS8ve2aa0IilXhrnrNceJCLt4gcjFhetGZjPWN8MPyzwDL6z+BazyF/Amc2TUOSi+VMxZfH6Jej1sFW6m+m/oEfhDgdmd3fwYWRtg7gopm66875zL7M8Rh7rOxjh5vU6cIs4V4LPDtAVzv5/MJu/z1C5COZ3IsH2H1PdmOG80uy8Mn/YVTBdsiQdVOQBxzw0vu2tW8tw==
    db_username: AgCFyHE08L8pD3+0lwfzD0mEECClgO9enewiUBHfJZ8H+bgnA7nz1AGBquAZSPzIrJDrF95RdIjuoc08vw3JatRNFG3uIy4UAlKnzGNGRxom07/BgIXLY+CLhnoKQY/fU/PXM8jgREBLOtjmOSpzxOq9Tu4saqleUbcT9YM+HQHQv554XoSv7EVfFnbOAgBinI+HPLA+mpFWZy6bObu0bxdhZGHXlJ72XHZODQEM+2WY1qEnOL1ZjOuvJVyUwXOCZdCS7NmNhmXjs9w7vwWQmLHlUGv8nOlwIEGCHD93+01C76NZlxrw0pqImgngJJwH0WA+mVdMe+VxoOvmmz1LgYfsB+++NfCwFQBn3NdQQVrztSqrCutHLo4XmG9c4kbqENbhnZs0pn8TA/wOix/oMu/29G86SaBtebKPf1DjVg3J5PB48v2wk4dbDBl8YwYXGwCpqCMeaqJh9QYbu2W2mAIjPBMeKsftH7W0V2o48Q+PGcgtnzOV7Ax1dv4xV8B926aZyH3F1kQIoL3wN5EinP56YxNCra1i4t5lGSg66P7r4d6aQn5bAjFoCwRUzIr1ABwW24Bi04WUiONGfy5ZDn4es8TT8kUzYYc3efb9tBDpqAUXwSCmGkl9ffoOFIdhkGD7eTWVJSfixIDavhxwi9CT1jj9F7FzGSV6xEHciJ7M+GWAVR3XpCPK6AzHChdfH0Fe6vLv+Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: memos-secrets
