apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: memos-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: db_password
      remoteRef:
        key: prod/cnpg/databases/memos
        property: password
    - secretKey: db_username
      remoteRef:
        key: prod/cnpg/databases/memos
        property: username