---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflared-tunnel-token-secret
  namespace: cloudflared
spec:
  encryptedData:
    api-token: AgB84PFB4OpNat8KiEpN6ppDZq2dJ7FrYSVNQQ1ylpS5qUx92qg5y5aM1RIG+55UJTkPiatO+6z5AE4rgYy/PhxDpGeMHD3PyPDwGExK63QT5C0yrSXwqVTyZms7U0CbdB0X1F/76yjY3/lMfx31KEE9hlcvZZQLg+P9M51aSJakoQwBaX8pPdeweQ1WvAoPZyV8tX/2wi2JS1inDKUR0SsCsyRNX85tfoWQvso8HL8elxunI1J5wPxwurLxg3yfr/U38J3eX3ltAIY1RgzHkdgXsjSN0SDjlvJWzmxtD4GYoaE9od1MJWNaipcWee++Op50ejmsclaEocSCsRX2Y3qihAtEc4AvBKnsW4ozgwRv5ye/CYEln4lOWbD1y4yaAMdhOYB6ACA35sUajLEFbtdJhsQ994IM7hq0i3+DOfO5TyDuqnjneGcv77bOSAhIVc+2bebONlMH/3cre4k+a0Qz1Z/jrWwjIZTsKAbRbf1cPEv+rOUZsR43boQJ6AYRx6fVz7XtImTHfaF1K2JYBijK6U2GyiLiFtX/upUl+Z1vc5d4KmWIlphhxl3QrAdf0SnhQN8ZmaY94XnvnqLKh7XzYeJGHbxlmEZC+qsEsPFI0RL+EPkPk+eBpZ71WpjPHAtoi3SPNoOM+tOkASCzuQK4TgHjGw9YeyUTEgReEpVv7DdHY6ycejT83vKzbarpd19T+yJH0i5tItQHhPGOODS6zVOC6eZcnRSwleU3s5cT6cIAEXKA1HrZLfaiRXDwEzYZbsoF/hjwlSySiqzEU4ZiB2ltfScYXokL8fp/dc9w+V6oI6rMK2bULZQTdZ8OFj4qOmuhy2z5dfhWL5L6si85jEU/M/8EOTHI9N0xvUzEErAjo8TKA4CYuJA5GTAfknO48lGkieQA3UB8tCX38vM29pm1WpTnFjGCu1XEngy41gqtloZ1yQwS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflared-tunnel-token-secret
      namespace: cloudflared
    type: Opaque
