---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflared-credentials-secret
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgC22QYiCSNLkXO6tjgTKdui1099EB19+1qBpGmIOji9uGYNzkM+tX2TrHWnBlpaXmatW2foUpbWvc0z2DVASiUIi8rC7/v6ZGIYpcRYvunAtcQhm8iLtu1DxwUflauz+pSDTPT60GwHzzlOsCeNbsuslzk/93fxvo0qZlx62lAtmvT3eEsgVOhKsSXu3d7ZNe9piS7eHorR5ZC1d2F/QUMXagGmXzrY9DLtbucEc9Zm65Iwl4XjVv/LYvIfeLB9VGsojW/VlOVeglO49umUc1bPVOgChfSPuUi7tSkiMQsYTDlej9bI+AzH+iRUldNDYiqubWHwyMP5ObMEO1jxh1D3jTKjj8B076Eryvx7rjDeHSXP2Tjve8/j5EAip4liXTdrQC922Uk0EVl36Nm1JTXP2OOYIl+p16AvOZFi2QOZIkAB46RycDnrC/4orU8tH/iLTXRPlXW58wgdLAvQbvdk4gNw4pEaBYZOV8VRKkHVXrQdkps9PVmgfC140bPRG6vpWIaGSU/oT1+AvQgIlAIW3PoiV+dOueV83zUNzE6ydLvC+0IPoobNOBPIQNM+u6fcHZSueEIY/9kaYc4U7SnN94Z6a13QF92RkHJvyZYdDD5JiKVSc26GCyA8qpFpwu2PKjC2SUPmxZ85MEKff8nR37Ou7gbaGwth4iwPfowKAoFy8I1dVdNyUOo8WDkUFH9xHVPHOA2ALML6tl0yJDHypWT8Ml2Fa+3F5MMMh62ovQvNMp1Zwl2MW9pZ8n6nT3qBVUNa+vcN+HqOXWz03yo0/IyaICWUbbekGjGSXM+qCTlWUEjDIyfubtIH43zWz/ybqMMOpy4cUUD2LREzhKb9ybsPcG/Ya4v1xWF2Z7SbYWE9hQ730BGI9Cn0uTB1lm7A+UVnVwWWzE/9lspXUSG+dbrHw1aPmsNABktNEm1/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflared-credentials-secret
    type: Opaque
