---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflared-credentials-secret
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAVnRdyBIJxAGWT4IymM4dUAakaKf9taPyFS9/toE9QDRmIhqtDHtB8t8FDe8LyhyZxUDgePCbPV+/Fil+8eiExNHfCNJLKtjAgCDfHHOrRJHQFCEOKM2xufhOBnpd9E08GbldzavJcBWoZDTpnPB5+vw5mZORL459Ky5OzbfnivY9cmAf8RX3CEZvLk0GlbrX1fPYqY3dmP4RWNmAuD2TdOGFBIZAmQ2Npg+IA+VgD6c5Hsh3YY80G6kXWiALhSNd9eNKzKks4ePStjDp6y71oRTEeJyT5Io0MPKpwrMlA28GwevT6QxBiU8LdUAGeDM2GWpijp6Q1K2YN9AMqz+hsZ4TXFbR6YIue7DJi7ShTMg1ldT0T8OUGGTMByMSfWFb42IbujvLn/CE9Rl10tmlj3Xs2ZQSl+ToJ6AXwklAQF6CHPF73XeVjxC3GAL7dCqkh2SMt+dtFMjAhtfRIWtcGHaSBsxf3TLWjW+L0NVB2oVEge4zJ82/0EjXN28hVYUPAxrkNCqHc3NIR+rfS/MBKsdKvQKzpdifmdXUA2m/u05rO5IJtnzEwJQROhfJ5L2NjS9kD8PSkrR/5CJ3Onse3WJT+2xU5MRldTrwYNA/7QrPWXtI7tIDrGLEixO51S9fivTVUzY/8YTatSFu1EwdAZCfygJBFybP/Y8QjCfGLfCJ57FF3wdl8JWF1F8dMXkL4ReehPCC+Ha4je8mE3spiXWXTtSU53f4dVGGWh26D7jTJwvYKKHDA0LRpsJBOwvw43EWlf6rCdZs9gDbBJ7BMzzgQWs1RiL2ozGUpnMUc548F+M6a6g882kzXPeGsSN0aD8r0bf1RI1czF4aXBC49hzGba7d69TlzY2TkiHEJoCQwCTa1NnPLFOrwYDH+5bFew0KH/0u6d+AuX+/LP5Zw1o3mvy6LRD8N7LG7dmcx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflared-credentials-secret
      namespace: cloudflared
    type: Opaque
