apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: paperless-db-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: prod/cnpg/databases/paperless