---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: paperless-db-creds
spec:
  encryptedData:
    password: AgAKahmGZDNcEaVmhCCxFEA5manmklCbW5P66adoWqVzXNO+wNFAcXGYJcdeY2Fn2LujwPWqs6noA/L4s7M8NeoekAI4XgyB/3CnLIrZDZTBVUeW3EZqLMA+xncSSSyLo7OFIde7Q4jIE10m9m9Ijv3KEw9nI0bcnwQiqrF2qLd8NQLYU/il5R9Egzs81Gq2d73qH92lP0SW+y4cgJfTx3qft7Aw4nIcy3zx1ez9JFzTwdxIw23axDUrImeobmsyBLYVyR6HmXgYcYSptYXk97GtS1h1YeJz4YSIt/QwxLHHmTMMF2ZyT1ssgfwsoXkYPglHXxYRFdRfjQO4d/0x2WXktNRjq2G6Owc8+8KpobhqQHWY1BBRRQR+5jPEisEYwgVOWj7mW90T9prdebHoUeju/BoixsktiVeLy5hoguzACHB3oqpRcn6ZpWET9NtKdOSxAns21G+YXkqXOwi+TzpP/ou9ued16pBYYU9zWhE7dk6acWmq2aw68DYEKQjcIx3l4pAzg2naAC+sGO/N1HtPCG54a9V0aNq/Hvp5VA6oXEcgaIP5su8a5h1np/8//V/p78hykpEQ6aAPJ15yMP5pPoZvfvLnlToDCvLwWqvJDOROk6SX8Uuy1xhHIxy0V1HXO9wHo/I0yrPTVzFP9gKbGNzqkF80nhezsDhE4gXNpN9jEEZw+SkXy9JiIiV1sq1ZvN8TB1Y3Q4JZ8urle4NZhaCaoWf7VtaPTQPaycSWOw==
    username: AgAI2+tZ+XwtBiuz7r2VL71Xmiv6xLGo8ZK5w9yzukVaIM+eQR+CTNDijBkpwqt4whcwI3c82eVmWupTvRs33x6z7whSdj3BNmlCL901kqzZtssFol4cR/ZG3+bdCQBt/MDcMK1t76Rp7SEEnE2z+lAL4APsQjLZgV+xWnTbWb68+sUqW680wVXmyZVXiKSIukm43wE1lp1R7LT9M/pGzqLTMIfoJCZdPuiRRLgCDJzR6b/5GL/oWg4OrQQIDEL82LqSqz7i3Lft0EKrO0q3nfT/xDEars2kQ+URngMPOI5+RcS9BQPT7dP3vIChtcc/H4oMQiBWCH+rFK/RtMIhy+JitsmswvhDTjAk/CvSPnUMoDCILthYdbJuSTHiUBrm6a7yaRh0z3lSXu8tJ5bIjyLNScihDyJNo6AuIOX5ZIUDW3qFNztwpkybTMbZhYQ2DVNz2LncjvWqhRmRv1IlLQffNi4GB4FBSntl3lrmCnPi0dvo9NGXTVTLrFJBE6RdOeZwV1Se8jaLOO4WSQQYb/WwF39ry5ViKRYVbJZVHbbFALm7zhp9/UNOJKKkrJrr2vMifT2ZBAGTjD6XsYCpLPOh62rUc0hzqGZli8o//v2ZEp5YjRt8+fJInO+9sAG/n2SSSp2LR4XrvjI46CVSyEkkPY/IWr9ehUIfKecr24gGmSE2EvqTExHRcl4JVUYEa7gU+iMBXVa36xE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        cnpg.io/reload: "true"
      name: paperless-db-creds
    type: kubernetes.io/basic-auth
