---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: paperless-db-creds
spec:
  encryptedData:
    password: AgCOWZWaXx89QtH97iq2mSKps83efQXcKiFFyvqpxkTFON0a4G4loPnPPO5Q7pm4zMyCUEwffpPYPgradz9iTTiLuSswrcTQHKKjgJLd4JeWnTf/bJ8FOhx7MpEukWW4edcixTc9phv09I5sD0qfBFtFoFsjgUw1UKxToGekvoj5ekQp+NVHqRBfinJJG6qDCkRQ6iziSD35We1D0S5ZmHmMToQql5rkn1HdNMjgR4/1cTKPz4xgLGzXQAQLR+YiSq87FRVLV4i3K8yF3zxLPOFw2aJLQBm79S8iHpKOmOy5KXhjF6vwZqH5z+vW3bMoMPbVTRr7LFhBeO6K46/NWzi8Xjnh1i7b6gk9ql1ka6cqXNu7yWmguKr3Uks+C8RoWefB5xM5xKszX7UqnuEpEitkMeirRoQjRZivt15oW8NeTYslk1aK6PRmrhqL+vwxN4bHMetZlKdeFzXOKBDk/hbsajRUwP75z3FQfQZKMrOwSUsjcUTRymCyLdhEUZXXvrZLEEZNW+e3+VVm0POdyMgSBNPCJ711u5XbzxoEkfOlmNSucht75KczCIPSvvZPQdfjmOCtZmXCJwyVBhL6yHJ9/x9oNRwKLWg88h4mqKZDt+Qtp3QLi6N9bRYPAtPHNxvaEmvRAG4vDOleGO2jeqZIdcq8bdf4Z6/RKJd5+Z46TB4RuVTCH26U4Vl2XgLwjNMjgpxMjEdL56Po65sG36M+/4Mh4mYlLKL//vnSXlYHSA==
    username: AgBEhjWpGMkKpa+LDUC73R5KfqmD4e7j+Aznd1JnDSQusIqKKXcjlenZoAnryrgBbDvWfuYZGF3wuiB/uAhzvNUYwkvST7MVk8H7But+2SDJ+eqprD9f9tlkVUWr0cJoJ6inbyTTAXv/7HVvPrOk05TXveKIy+b4EdYcXliZrHC7nm7xowne1jgM+cWU7OZ4iGXwQYJ5OBNfe/wXpGtFw9XDq91ixRXfsBTbYvHbmredYytbBxu+QwVEkOR/0wAJUA+lWy/UyROrUGcsrQhVhFajjuHf3yPSvOjbMDgzGQLn4iE8vJSfYkAb9ddaj9QNrfhpOzs0CVU8fYD6iCvFZDEj7V80kCSJNLCj1rDqlc7O1f7gWE0UmYLbqosYaEbd6fGq0AlcvmkBggPwqSpxpiGi7HMqV8Ps0v0ZPm5+twiDGZqqc0cnUQeb8HXmcHfGZeIZ7yN4rjz5hasvtEW/nhYXaXqZsM974hS7sedKBLAI8/NLe1S+SUC9+mfOexF1vS4D+bX/jMRYujAbto2cnnjxarQpCSzrWlAYwmXiQ4VT4Ryq4FR3tQtjkCYxw7iZVgG71WDDaCEAJ7JHV52y/KsaBk4DVrfdtHcl3+ID+oGRy3CTCG4i1+3KU3/cHXo8NS97yExDctWEJQTwpyEy5pHbTnYNPY+worWhz7ObqWjBjmq4A/k74bF+M/557J4bThMNlcqpeqlJRx0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        cnpg.io/reload: "true"
      name: paperless-db-creds
    type: kubernetes.io/basic-auth
