---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: fireflyiii-db-creds
spec:
  encryptedData:
    password: AgBh1BMWxjPbY+s8D1RRyM0MjhaGCMpkYJe1mEBIchE764ozzbHZbEux2I1Txm0fBvVsUS+xxzt6m74dmHP++vhY/afSpmTpMWGTRLmrIFex+s1RBoh6wS4dslsyRzmtsCoMhamvDfczqjOxc34gxATGugGIc39XoHo0i9YSNCoNMEN26/6ktUACDFVNLp3TtuPCHBc/wd1UPqgfrtfowon5KDPk0dc0P/PddpGjtVz2aG5L0VrULomzqwOzH1QScI2uyaSYV1iqJDmK1b7TYQ2ejb6KMmJYxxnVdPOpK8PLzbH5NWBQ3SmAH0komiO/0EifuaHj2Udtq/9n3Q6SzKuDOHFSC0ZpTPcs/1Bhw66HaJGMd8s2uj2adJSNQwrt751PJXnzVf5+9k2V1SETmH46vCZdDuK9t1KwwSOE0I0T16n0tplYMaumOdNX/IptZ4frwgtOGMQbZP5dzN6/P9OQwvTaAhY4ca4MhALFaMgZx+CuwuEjMaZ54LzrOXL+d9Z9ZUzO0Q3/tsnM0IwG7F/Qq2lN3nNs2tGQr8H7cRxToRLoA2eqCvy8ZQ2Sz1L1yij/Tz2Tk2NE+fC1Y+0QA9rO8tsri+0C1NwM/Zprtxg5U/dGWQCrE9iEmgLGmv7mKfMlWHSFNtkgB6QXhevUSTCiXSTJyvQDlf3U5BX3mY5DYJRABdUYCHQpZagrhpq49YWgQPrA9i90gP6/GM/qXH9tzAOYfhPPolHp4J8KVrEULg==
    username: AgBPjdEeI+zIU+A+NKXDgFTeN+Gty18U/v4tExAPVlPz9UJrpWNKqca7dab9hmUJCo7FxJY5qonjj4fRVTTHTBro7fqkS5bXnWe1bgzEN4Xi9dXVynfNVpAyeUb6byq/IGHNi0BOyQhU6h9vVFMGtyvx5rlMhf80P609TioULwxpHPVqhQ1jG8HZd9ne845azGpWyA9YdbuKF1dXLoJg6xKdWxGuogXySI2T6nE6vyQLUV0w1eAEozCIp0u3n6z6ZJrRVSNqz/HeFgantxr+8yH/NvJusTA/JsPpsqdNTqRMo5NfD23tndJ7X6CLhVznHDvNbGG/8bGOHXAiJa/fm4E0GfXrpsZjeb7OPxk5EiGlitumMuuZZ3DSlwB3q5e2TRZcBKzgknn7akZ8NF+jEN8mPrTGlXtFYfy7/l5UxlEAI4sXK5ZhRIjLL5zLV9ScUUG893hS1qTuoYwm/T2gBqR50l81TVk23XiU/Qnj8b2mJmPQ1bypTMAgB1Qe0Wi2y0lV/DU638PMTvBltEOFocVLZ7ecnuWP4ido+ao2byvAd5hMpw0WZ9E9KgycePmXtQAPfSLhVYQ79odsjn9tiKup/Brb9le2/NDRMRow9YQyzYtVsn5xhCJe0HkFwFYprTZeS57hBw55ZKm1ef0q+o2hOmAnd2fwtfNb3YilWBbcg87nFzJ3eWWA+TcO8O3v7vL+M4i4K8ovMycW
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        cnpg.io/reload: "true"
      name: fireflyiii-db-creds
    type: kubernetes.io/basic-auth
