---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: fireflyiii-db-creds
spec:
  encryptedData:
    password: AgBp52YmtpxAKvx2bkle4LJ88whjHp8WnbGADb/sJJ5+P3F5+JwNNL/9JzNTbV8Jy9ZMsg+iQ5vgLvc0K9FiObdVXeXJmkKpjSZX0HqawAViqEI3GBKnMDZC6uq4E4R4ddm0Oq/UEIgEhJvABDm1qaznjEDzB1yQzOr5z6WANttbbwkvyroxCUIErV39OiPGJ1rENxFrSY2ZWlaFlarqejU1BS1nfmljHi0vBLir9cKidbPbarbvpIT3d2DixF0i8lSCK7p6KuVdqQz82YfBjMWEdEg7gq4AL9L6RH+tP3FxGr8WIzRwKv+wcEkBWhFdW7TuNhY6Vzz/8wz40yiIT6E/j9xdbEy6B6LdwyNU0ga6/RwwT2K51vF3waLroMhK+L63kBjhzWPaAf5FAxmqV4wPSc6FrXP8yB6V1TtNHm1FVWj6ERyTAcOynQ+mnkXDeyuV4ntCIgoqBD5SJXTVAZWv9ywyTGZ4xWpJkZSLwilUcdjdRiVUvRrznCz+EV12vSledzmqJPhNU5Pl6Afu4eWNmHxeClCFxhoPZ/X5im4vvFoBgGmh44klDoze11ugkKK6uUg5TLL+8sTYRLLrkge2nIzd0/OHkuJOFs4jI2P/Wy+PW7IKroQNwa62uOCsCMdYV6sq9i0O80U5remenfMV5LUvAVkTaYm/jllMt4V3SZvcZ3rm+PEHZuiboXjJLeAmCT+fhSRDxNXG2PxA2LS8OhyDOyTUXulqn1u914MGrg==
    username: AgBcwT24W3HJHMtY6g5BjfialhkhRtJIv/KIw8OIBkyFgxkDBR2Mp08xEZd/fV602KuvlfMxkz1cmDl1Y8SLDwrJln1V03/CJsFHCbQjTS2yMKfKRAU3vaQKCpQGlrqRIrc0QzfIi2n5tZvXWpT1/1pAFy5MntfqaCM/DXNDL6+3NnPR612omH8ZZLO8aB3NGYW3hhZmisZTgLiJBzmKKz+4fts7VLt0UuXIJKY/bMkMCzd18HJex0zEnsHTeBykq1rAry/MOYxkvNdCKHAtsQZ39+Ddo8yZrFAp+vkFDG1nJDoo95zn5NdBvcvTKMNlOT3YyKJzWp/HN5MhQqGp/qkXbPsoOlT6f2CCoX5F4E6FsXMXDT/pB3WpqEpHHuQVie+oLrivOq9ciB2usiuycsVQAu07ISzW6sTEsyg9RDC/+XlCkI1/X6/92VBVHOQElol7caA3yl5B1vfqcOM86rskdw4wyrs9oIlrCC6PUu4kZ063rsJHiIOYzEZOSq/S9x31dmE7BukcZ90jLbXz6VMsh76nM1ZMY++IuwT2PR8vXqym+vQXQZIlS+FBz8hE6R4XaB7epIN9eIkgu9xC3Neq8yfStdZlcynxCIEsqcvS1OGQfzAf6H1pEkfbRi+r872ThpEEyNDq/oNFaHi5h8dMwIU7wzw0V+odXsfIaHuvi34/8l6cEPNDvyiiJNIedJ8uNkcCsW3ITjQu
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        cnpg.io/reload: "true"
      name: fireflyiii-db-creds
    type: kubernetes.io/basic-auth
