apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg

resources:
  - cluster.yaml
  - fireflyiii-db-secret-sealed.yaml
  - ../../../../base/cnpg-db/
  
patches:
  - target:
      group: cilium.io
      version: v2
      kind: CiliumNetworkPolicy
      name: default-database-netpol
    patch: |-
      - op: replace
        path: /metadata/name
        value: fireflyiii-database-netpol
      - op: replace
        path: /spec/endpointSelector/matchLabels/cnpg.io~1cluster
        value: fireflyiii-database
      - op: replace
        path: /spec/egress/0/toEndpoints/0/matchLabels/cnpg.io~1cluster
        value: fireflyiii-database
      - op: replace
        path: /spec/ingress/0/fromEndpoints/0/matchLabels/app
        value: fireflyiii
      - op: replace
        path: /spec/ingress/0/fromEndpoints/0/matchLabels/k8s:io.kubernetes.pod.namespace
        value: fireflyiii
      - op: add
        path: /spec/ingress/0/fromEndpoints/0/matchLabels/tier
        value: core
      - op: replace
        path: /spec/ingress/1/fromEndpoints/0/matchLabels/cnpg.io~1cluster
        value: fireflyiii-database
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: ScheduledBackup
      name: default-scheduled-backup
    patch: |-
      - op: replace
        path: /metadata/name
        value: fireflyiii-db-backup
      - op: replace
        path: /spec/cluster/name
        value: fireflyiii-database