apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: pgadmin-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: prod/management/pgadmin
        property: PGADMIN_DEFAULT_EMAIL
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: prod/management/pgadmin
        property: PGADMIN_DEFAULT_PASSWORD