apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: paperless-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: admin_email
      remoteRef:
        key: prod/apps/paperless
        property: admin_email
    - secretKey: admin_password
      remoteRef:
        key: prod/apps/paperless
        property: admin_password
    - secretKey: admin_user
      remoteRef:
        key: prod/apps/paperless
        property: admin_user
    - secretKey: db_password
      remoteRef:
        key: prod/cnpg/databases/paperless
        property: password
    - secretKey: db_username
      remoteRef:
        key: prod/cnpg/databases/paperless
        property: username
    - secretKey: redis_password
      remoteRef:
        key: prod/apps/paperless
        property: redis_password
    - secretKey: secret_key
      remoteRef:
        key: prod/apps/paperless
        property: secret_key