apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg

labels:
  - pairs:
      app.kubernetes.io/name: cloudnative-pg
      app.kubernetes.io/managed-by: argocd
    includeSelectors: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"

resources:
  - namespace.yaml
  - rbac.yaml

helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.26.1
    releaseName: cloudnative-pg-operator
    namespace: cloudnative-pg
    valuesFile: values.yaml
    includeCRDs: true
