apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: sops
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    sops:
      engine: "sops"
      sopsConfig:
        age:
          secretRef:
            name: sops-age
            key: age.agekey
            namespace: external-secrets
