apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      server: "http://vault.svc.cluster.local:8200"
      path: "secret"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: external-secrets