apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "30s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
  data:
    - secretKey: vault-token
      remoteRef:
        key: secret/data/external-secrets/vault
        property: token