apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - cluster-secret-store.yaml
  - namespace.yaml
helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.18.2
    releaseName: external-secrets
    valuesFile: values.yaml
    includeCRDs: true

# Since the CRDs are not approved, we need to patch them to avoid issues with the conversion strategy. 
patches:
  - patch: |
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: externalsecrets.external-secrets.io
        annotations:
          "api-approved.kubernetes.io": "unapproved, request-not-required"
          "external-secrets.io/conversion-strategy": "none"
  - patch: |
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: clustersecretstores.external-secrets.io
        annotations:
          "api-approved.kubernetes.io": "unapproved, request-not-required"
          "external-secrets.io/conversion-strategy": "none"
