apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: goti-stack-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: goti-stack-config-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: prod/monitor/goti-stack
        property: username
    - secretKey: password
      remoteRef:
        key: prod/monitor/goti-stack
        property: password
    - secretKey: telegram-bot-token
      remoteRef:
        key: prod/monitor/goti-stack
        property: telegram-bot-token
    - secretKey: telegram-chat-id
      remoteRef:
        key: prod/monitor/goti-stack
        property: telegram-chat-id
    - secretKey: timezone
      remoteRef:
        key: prod/monitor/goti-stack
        property: timezone