apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
data:
  # See the docs: https://docs.paperless-ngx.com/configuration/
  ## Paths and folders
  PAPERLESS_FILENAME_FORMAT: "{owner_username}/{{ created }}/{{ title }}"
  ## Authentication and SSO
  PAPERLESS_ACCOUNT_ALLOW_SIGNUPS: "false"
  ## OCR
  PAPERLESS_OCR_LANGUAGE: "por"
  PAPERLESS_OCR_LANGUAGES: "eng por"  # Belongs to Container specific options
  PAPERLESS_OCR_MODE: "skip"
  PAPERLESS_OCR_SKIP_ARCHIVE_FILE: "never"
  PAPERLESS_OCR_CLEAN: "clean"
  PAPERLESS_OCR_DESKEW: "true"
  PAPERLESS_OCR_ROTATE_PAGES: "true"
  PAPERLESS_OCR_OUTPUT_TYPE: "pdfa"
  ## Software Tweaks
  PAPERLESS_TASK_WORKERS: "1"
  PAPERLESS_THREADS_PER_WORKER: "1" # PAPERLESS_TASK_WORKERS * PAPERLESS_THREADS_PER_WORKER does not exceed your CPU core count or else paperless will be extremely slow
  PAPERLESS_WORKER_TIMEOUT: "300"
  PAPERLESS_TIME_ZONE: "Europe/Lisbon"
  PAPERLESS_ENABLE_NLTK: "1"
  PAPERLESS_DATE_PARSER_LANGUAGES: "pt-PT+en"
  ## Document Consumption
  PAPERLESS_CONSUMER_DELETE_DUPLICATES: "false"
  PAPERLESS_CONSUMER_RECURSIVE: "true"
  PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
  PAPERLESS_FILENAME_DATE_ORDER: "YMD"
  ## Polling
  PAPERLESS_CONSUMER_POLLING: "0"
  ## Audit Trail
  PAPERLESS_AUDIT_LOG_ENABLED: "true"
  ## Containers specific options
  PAPERLESS_WEBSERVER_WORKERS: "2"
  USERMAP_UID: "1000"
  USERMAP_GID: "1000"