apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
    
labels:
  - pairs:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/component: web
      app.kubernetes.io/part-of: paperless

resources:
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - cilium-netpol.yaml