apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-pvc
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/important: enabled
    recurring-job-group.longhorn.io/default: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media-pvc
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/important: enabled
    recurring-job-group.longhorn.io/default: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-export-pvc
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume-pvc
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn