apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-runner-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: arc-runner-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: github_token
      remoteRef:
        key: prod/controllers/arc-runners
        property: GITHUB_TOKEN
